const fs = require('fs');
const path = require('path');

const scriptPath = path.join(__dirname, 'script.js');
let scriptContent = fs.readFileSync(scriptPath, 'utf8');

// The original English translation to be used as a template for new languages
const en = {
    "title": "LinkedIn or Interpol",
    "subtitle": "Professional or Criminal? You decide!",
    "score": "Score",
    "total": "Total",
    "autoAdvance": "Auto-Advance",
    "linkedinButton": "LinkedIn",
    "interpolButton": "Interpol",
    "nextButton": "Next Image",
    "footerTitle": "LinkedIn or Interpol - A Deduction Game - Version 1.0",
    "footerDisclaimer": "Disclaimer: This website is a satirical and educational guessing game.",
    "privacyPolicy": "Privacy Policy",
    "termsOfService": "Terms of Service",
    "copyright": "© 2025 Jan Queralt. All rights reserved.",
    "correct": "Correct!",
    "wrong": "Wrong!",
    "policeRecord": "Police Record",
    "imgDesc1": "This person is on LinkedIn.",
    "imgDesc2": "Iranian indicted for hacking by FBI.",
    "imgDesc3": "This person is on LinkedIn.",
    "imgDesc4": "Drug trafficking and distribution case by FBI.",
    "imgDesc5": "This person is on LinkedIn.",
    "imgDesc6": "Conspiracy and foreign agent charges.",
    "imgDesc7": "This person is on LinkedIn.",
    "imgDesc8": "Kulkov indicted for cybercrime.",
    "imgDesc9": "This person is on LinkedIn.",
    "imgDesc10": "Radovanovic charged with swatting conspiracy.",
    "imgDesc11": "This person is on LinkedIn.",
    "imgDesc12": "Sokolov indicted for credit card fraud.",
    "imgDesc13": "This person is on LinkedIn.",
    "imgDesc14": "Fentanyl and weapons trafficking conspiracy.",
    "imgDesc15": "This person is on LinkedIn.",
    "imgDesc16": "Drug distribution conspiracy charges.",
    "imgDesc17": "This person is on LinkedIn.",
    "imgDesc18": "is part of the PSOE criminal organization",
    "imgDesc19": "This person is on LinkedIn.",
    "imgDesc20": "Child abduction by Smrekar.",
    "imgDesc21": "This person is on LinkedIn.",
    "imgDesc22": "International arrest warrants issued for assassination plot.",
    "imgDesc23": "This person is on LinkedIn.",
    "imgDesc24": "Steffen van Khoa DO wanted for cocaine robbery.",
    "imgDesc25": "This person is on LinkedIn.",
    "imgDesc26": "wanted for corruption in Taiwan.",
    "imgDesc27": "This person is on LinkedIn.",
    "imgDesc28": "Terrorism and cybercrime charges.",
    "imgDesc29": "This person is on LinkedIn.",
    "imgDesc30": " wanted for murder and attempted murder.",
    "imgDesc31": "This person is on LinkedIn.",
    "imgDesc32": "Lester Eubanks wanted for murder and escape.",
    "imgDesc33": "This person is on LinkedIn.",
    "imgDesc35": "This person is on LinkedIn.",
    "imgDesc37": "This person is on LinkedIn.",
    "imgDesc39": "This person is on LinkedIn.",
    "imgDesc41": "This person is on LinkedIn.",
    "imgDesc43": "This person is on LinkedIn.",
    "imgDesc45": "This person is on LinkedIn.",
    "imgDesc47": "This person is on LinkedIn.",
    "imgDesc49": "This person is on LinkedIn.",
    "professionalOrCriminal": "Professional or Criminal?",
    "youDecide": "You decide!",
    "aDeductionGame": "A Deduction Game",
    "version": "Version 1.0",
    "disclaimer": "Disclaimer: This website is a satirical and educational guessing game.",
    "allRightsReserved": "All rights reserved.",
    "metaDescription": "A fun game where you have to guess if a person is a LinkedIn professional or an Interpol criminal.",
    "ogTitle": "LinkedIn or Interpol",
    "ogDescription": "A fun game where you have to guess if a person is a LinkedIn professional or an Interpol criminal.",
    "aboutTitle": "About - LinkedIn or Interpol",
    "aboutHeader": "About the Game",
    "aboutText": "This game was created for entertainment and educational purposes to highlight the similarities and differences in professional and criminal profiles. All images are used for satirical purposes.",
    "disclaimerTitle": "Disclaimer - LinkedIn or Interpol",
    "disclaimerHeader": "Disclaimer",
    "disclaimerText": "This website is a satirical and educational guessing game. It is not affiliated with LinkedIn or Interpol. All content is for entertainment purposes only.",
    "backButton": "Back to the game",
    "aboutButton": "About",
    "disclaimerButton": "Disclaimer",
    "metaKeywords": "linkedin, interpol, game, professional, criminal, guess",
    "privacyTitle": "Privacy Policy - LinkedIn or Interpol",
    "privacyHeaderV2": "Privacy Policy",
    "privacyIntro": "Welcome to our website. We want you to understand what information we collect and how we use it. To make this game better and keep it free, we use services like Google Analytics.",
    "whatDataHeader": "What Information Do We Collect?",
    "whatDataText1": "When you use our site, we automatically collect some information to help us understand our audience. This includes:",
    "whatDataPoint1": "<b>General Location and Device Information:</b> We collect data like your city and what type of device you are using. This helps us know where our users are from and how they access the site.",
    "whatDataPoint2": "<b>Usage Data:</b> We see how you interact with the game, which helps us improve the user experience.",
    "whatDataPoint3": "<b>Google Account Information:</b> If you are logged into a Google account and have ad personalization enabled, Google may share anonymous demographic information with us, such as your age range or interests. We do not receive any of your personal information, like your name or email.",
    "howDataHeader": "How Do We Use This Information?",
    "howDataText1": "The data we collect helps us:",
    "howDataPoint1": "Improve and optimize our website and game.",
    "howDataPoint2": "Show you ads that are more relevant to your interests.",
    "yourChoicesHeader": "Your Data and Your Choices",
    "yourChoicesText1": "We respect your privacy. You can control and manage the information Google collects about you by visiting Google's <a href=\\"https://myactivity.google.com/myactivity\\" target=\\"_blank\\">My Activity</a> page. There, you can review and delete your activity data and adjust your ad personalization settings.",
    "yourConsentHeader": "Your Consent",
    "yourConsentText1": "By using our website, you consent to our data collection and privacy policy as described here.",
    "privacyButton": "Privacy Policy",
    "cookieBannerText": "This website uses cookies to ensure you get the best experience on our website.",
    "learnMore": "Learn more",
    "cookieAccept": "Got it!",
    "requestImageBtn": "Request to Add an Image",
    "requestImagePopupHeader": "Request a New Image",
    "requestImagePopupNameLabel": "Name:",
    "requestImagePopupLinkLabel": "Image Link:",
    "requestImagePopupTypeLabel": "Type:",
    "requestImagePopupTypeLinkedin": "LinkedIn",
    "requestImagePopupTypeInterpol": "Interpol",
    "requestImagePopupSubmit": "Submit Request",
    "structuredDataDescription": "A fun game where you have to guess if a person is a LinkedIn professional or an Interpol criminal.",
    "structuredDataType": "Deduction game",
    "instructionsBtn": "Instructions",
    "instructionsPopupHeader": "How to Play",
    "instructionsPopupText1": "You will be shown a series of images.",
    "instructionsPopupText2": "For each image, you must guess whether the person is a professional from LinkedIn or a criminal from Interpol.",
    "instructionsPopupText3": "Click the \\"LinkedIn\\" or \\"Interpol\\" button to make your guess.",
    "instructionsPopupText4": "Your score is tracked at the top of the page.",
    "playButton": "Play",
    "shareScoreButton": "Share Score"
};

// Manually sorted list of all required languages
const sortedTranslations = {
    "am": en, "ar": en, "ay": en, "bn": en, "ca": en, "de": en, "el": en, "en": en, "es": en, "eu": en, "fa": en, "fi": en, "fj": en, "fr": en, "ga": en, "gd": en, "gn": en, "ha": en, "he": en, "hi": en, "hu": en, "id": en, "it": en, "ja": en, "jv": en, "ko": en, "mi": en, "mr": en, "my": en, "nl": en, "nv": en, "pa": en, "pl": en, "pt": en, "qu": en, "ru": en, "so": en, "su": en, "sw": en, "ta": en, "te": en, "th": en, "tl": en, "tr": en, "uk": en, "ur": en, "vi": en, "wo": en, "yo": en, "zh": en, "zu": en
};

const newTranslationsDeclaration = `const translations = ${JSON.stringify(sortedTranslations, null, 4)};`;

const regex = /const translations = \{[\s\S]*?\};/;
const newScriptContent = scriptContent.replace(regex, newTranslationsDeclaration);

fs.writeFileSync(scriptPath, newScriptContent, 'utf8');

console.log('Successfully sorted and added all new languages to script.js');
