const translations = {
    "en": {
        "title": "LinkedIn or Interpol",
        "subtitle": "Professional or Criminal? You decide!",
        "score": "Score",
        "total": "Total",
        "autoAdvance": "Auto-Advance",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Next Image",
        "footerTitle": "LinkedIn or Interpol - A Deduction Game - Version 1.0",
        "footerDisclaimer": "Disclaimer: This website is a satirical and educational guessing game.",
        "privacyPolicy": "Privacy Policy",
        "termsOfService": "Terms of Service",
        "copyright": "© 2025 Jan Queralt. All rights reserved.",
        "correct": "Correct!",
        "wrong": "Wrong!",
        "policeRecord": "Police Record",
        "imgDesc1": "This person is on LinkedIn.",
        "imgDesc2": "Iranian indicted for hacking by FBI.",
        "imgDesc3": "This person is on LinkedIn.",
        "imgDesc4": "Drug trafficking and distribution case by FBI.",
        "imgDesc5": "This person is on LinkedIn.",
        "imgDesc6": "Conspiracy and foreign agent charges.",
        "imgDesc7": "This person is on LinkedIn.",
        "imgDesc8": "Kulkov indicted for cybercrime.",
        "imgDesc9": "This person is on LinkedIn.",
        "imgDesc10": "Radovanovic charged with swatting conspiracy.",
        "imgDesc11": "This person is on LinkedIn.",
        "imgDesc12": "Sokolov indicted for credit card fraud.",
        "imgDesc13": "This person is on LinkedIn.",
        "imgDesc14": "Fentanyl and weapons trafficking conspiracy.",
        "imgDesc15": "This person is on LinkedIn.",
        "imgDesc16": "Drug distribution conspiracy charges.",
        "imgDesc17": "This person is on LinkedIn.",
        "imgDesc18": "is part of the PSOE criminal organization",
        "imgDesc19": "This person is on LinkedIn.",
        "imgDesc20": "Child abduction by Smrekar.",
        "imgDesc21": "This person is on LinkedIn.",
        "imgDesc22": "International arrest warrants issued for assassination plot.",
        "imgDesc23": "This person is on LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO wanted for cocaine robbery.",
        "imgDesc25": "This person is on LinkedIn.",
        "imgDesc26": "wanted for corruption in Taiwan.",
        "imgDesc27": "This person is on LinkedIn.",
        "imgDesc28": "Terrorism and cybercrime charges.",
        "imgDesc29": "This person is on LinkedIn.",
        "imgDesc30": " wanted for murder and attempted murder.",
        "imgDesc31": "This person is on LinkedIn.",
        "imgDesc32": "Lester Eubanks wanted for murder and escape.",
        "imgDesc33": "This person is on LinkedIn.",
        "imgDesc35": "This person is on LinkedIn.",
        "imgDesc37": "This person is on LinkedIn.",
        "imgDesc39": "This person is on LinkedIn.",
        "imgDesc41": "This person is on LinkedIn.",
        "imgDesc43": "This person is on LinkedIn.",
        "imgDesc45": "This person is on LinkedIn.",
        "imgDesc47": "This person is on LinkedIn.",
        "imgDesc49": "This person is on LinkedIn.",
        "professionalOrCriminal": "Professional or Criminal?",
        "youDecide": "You decide!",
        "aDeductionGame": "A Deduction Game",
        "version": "Version 1.0",
        "disclaimer": "Disclaimer: This website is a satirical and educational guessing game.",
        "allRightsReserved": "All rights reserved.",
        "metaDescription": "A fun game where you have to guess if a person is a LinkedIn professional or an Interpol criminal.",
        "ogTitle": "LinkedIn or Interpol",
        "ogDescription": "A fun game where you have to guess if a person is a LinkedIn professional or an Interpol criminal.",
        "aboutTitle": "About - LinkedIn or Interpol",
        "aboutHeader": "About the Game",
        "aboutText": "This game was created for entertainment and educational purposes to highlight the similarities and differences in professional and criminal profiles. All images are used for satirical purposes.",
        "disclaimerTitle": "Disclaimer - LinkedIn or Interpol",
        "disclaimerHeader": "Disclaimer",
        "disclaimerText": "This website is a satirical and educational guessing game. It is not affiliated with LinkedIn or Interpol. All content is for entertainment purposes only.",
        "backButton": "Back to the game",
        "aboutButton": "About",
        "disclaimerButton": "Disclaimer",
        "metaKeywords": "linkedin, interpol, game, professional, criminal, guess",
        "privacyTitle": "Privacy Policy - LinkedIn or Interpol",
        "privacyHeaderV2": "Privacy Policy",
        "privacyIntro": "Welcome to our website. We want you to understand what information we collect and how we use it. To make this game better and keep it free, we use services like Google Analytics.",
        "whatDataHeader": "What Information Do We Collect?",
        "whatDataText1": "When you use our site, we automatically collect some information to help us understand our audience. This includes:",
        "whatDataPoint1": "<b>General Location and Device Information:</b> We collect data like your city and what type of device you are using. This helps us know where our users are from and how they access the site.",
        "whatDataPoint2": "<b>Usage Data:</b> We see how you interact with the game, which helps us improve the user experience.",
        "whatDataPoint3": "<b>Google Account Information:</b> If you are logged into a Google account and have ad personalization enabled, Google may share anonymous demographic information with us, such as your age range or interests. We do not receive any of your personal information, like your name or email.",
        "howDataHeader": "How Do We Use This Information?",
        "howDataText1": "The data we collect helps us:",
        "howDataPoint1": "Improve and optimize our website and game.",
        "howDataPoint2": "Show you ads that are more relevant to your interests.",
        "yourChoicesHeader": "Your Data and Your Choices",
        "yourChoicesText1": "We respect your privacy. You can control and manage the information Google collects about you by visiting Google's <a href=\"https://myactivity.google.com/myactivity\" target=\"_blank\">My Activity</a> page. There, you can review and delete your activity data and adjust your ad personalization settings.",
        "yourConsentHeader": "Your Consent",
        "yourConsentText1": "By using our website, you consent to our data collection and privacy policy as described here.",
        "privacyButton": "Privacy Policy",
        "learnMore": "Learn more",
        "cookieAccept": "Got it!",
        "requestImageBtn": "Request to Add an Image",
        "requestImagePopupHeader": "Request a New Image",
        "requestImagePopupNameLabel": "Name:",
        "requestImagePopupLinkLabel": "Image Link:",
        "requestImagePopupTypeLabel": "Type:",
        "requestImagePopupTypeLinkedin": "LinkedIn",
        "requestImagePopupTypeInterpol": "Interpol",
        "requestImagePopupSubmit": "Submit Request",
        "structuredDataDescription": "A fun game where you have to guess if a person is a LinkedIn professional or an Interpol criminal.",
        "structuredDataType": "Deduction game",
        "instructionsBtn": "Instructions",
        "instructionsPopupHeader": "How to Play",
        "instructionsPopupText1": "You will be shown a series of images.",
        "instructionsPopupText2": "For each image, you must guess whether the person is a professional from LinkedIn or a criminal from Interpol.",
        "instructionsPopupText3": "Click the \"LinkedIn\" or \"Interpol\" button to make your guess.",
        "instructionsPopupText4": "Your score is tracked at the top of the page.",
        "playButton": "Play"
    },
    "es": {
        "title": "LinkedIn o Interpol",
        "subtitle": "¿Profesional o Criminal? ¡Tú decides!",
        "score": "Puntuación",
        "total": "Total",
        "autoAdvance": "Avance Automático",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Siguiente Imagen",
        "footerTitle": "LinkedIn o Interpol - Un Juego de Deducción - Versión 1.0",
        "footerDisclaimer": "Aviso: Este sitio web es un juego de adivinanzas satírico y educativo.",
        "privacyPolicy": "Política de Privacidad",
        "termsOfService": "Términos de Servicio",
        "copyright": "© 2025 Jan Queralt. Todos los derechos reservados.",
        "correct": "¡Correcto!",
        "wrong": "¡Incorrecto!",
        "policeRecord": "Antecedentes Policiales",
        "imgDesc1": "Esta persona está en LinkedIn.",
        "imgDesc2": "Iraní acusado de piratería por el FBI.",
        "imgDesc3": "Esta persona está en LinkedIn.",
        "imgDesc4": "Caso de narcotráfico y distribución por el FBI.",
        "imgDesc5": "Esta persona está en LinkedIn.",
        "imgDesc6": "Cargos de conspiración y agente extranjero.",
        "imgDesc7": "Esta persona está en LinkedIn.",
        "imgDesc8": "Kulkov acusado de ciberdelincuencia.",
        "imgDesc9": "Esta persona está en LinkedIn.",
        "imgDesc10": "Radovanovic acusado de conspiración de swatting.",
        "imgDesc11": "Esta persona está en LinkedIn.",
        "imgDesc12": "Sokolov acusado de fraude con tarjetas de crédito.",
        "imgDesc13": "Esta persona está en LinkedIn.",
        "imgDesc14": "Conspiración de tráfico de fentanilo y armas.",
        "imgDesc15": "Esta persona está en LinkedIn.",
        "imgDesc16": "Cargos de conspiración para distribuir drogas.",
        "imgDesc17": "Esta persona está en LinkedIn.",
        "imgDesc18": "forma parte de la organización criminal PSOE",
        "imgDesc19": "Esta persona está en LinkedIn.",
        "imgDesc20": "Secuestro de menores por Smrekar.",
        "imgDesc21": "Esta persona está en LinkedIn.",
        "imgDesc22": "Órdenes de arresto internacionales emitidas por complot de asesinato.",
        "imgDesc23": "Esta persona está en LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO buscado por robo de cocaína.",
        "imgDesc25": "Esta persona está en LinkedIn.",
        "imgDesc26": "buscado por corrupción en Taiwán.",
        "imgDesc27": "Esta persona está en LinkedIn.",
        "imgDesc28": "Cargos de terrorismo y ciberdelincuencia.",
        "imgDesc29": "Esta persona está en LinkedIn.",
        "imgDesc30": "buscado por asesinato y tentativa de asesinato.",
        "imgDesc31": "Esta persona está en LinkedIn.",
        "imgDesc32": "Lester Eubanks buscado por asesinato y fuga.",
        "imgDesc33": "Esta persona está en LinkedIn.",
        "imgDesc35": "Esta persona está en LinkedIn.",
        "imgDesc37": "Esta persona está en LinkedIn.",
        "imgDesc39": "Esta persona está en LinkedIn.",
        "imgDesc41": "Esta persona está en LinkedIn.",
        "imgDesc43": "Esta persona está en LinkedIn.",
        "imgDesc45": "Esta personá está en LinkedIn.",
        "imgDesc47": "Esta persona está en LinkedIn.",
        "imgDesc49": "Esta persona está en LinkedIn.",
        "professionalOrCriminal": "¿Profesional o Criminal?",
        "youDecide": "¡Tú decides!",
        "aDeductionGame": "Un Juego de Deducción",
        "version": "Versión 1.0",
        "disclaimer": "Aviso: Este sitio web es un juego de adivinanzas satírico y educativo.",
        "allRightsReserved": "Todos los derechos reservados.",
        "metaDescription": "Un divertido juego donde tienes que adivinar si una persona es un profesional de LinkedIn o un criminal de Interpol.",
        "ogTitle": "LinkedIn o Interpol",
        "ogDescription": "Un divertido juego donde tienes que adivinar si una persona es un profesional de LinkedIn o un criminal de Interpol.",
        "aboutTitle": "Acerca de - LinkedIn o Interpol",
        "aboutHeader": "Acerca del Juego",
        "aboutText": "Este juego fue creado con fines de entretenimiento y educativos para resaltar las similitudes y diferencias en los perfiles profesionales y criminales. Todas las imágenes se utilizan con fines satíricos.",
        "disclaimerTitle": "Aviso Legal - LinkedIn o Interpol",
        "disclaimerHeader": "Aviso Legal",
        "disclaimerText": "Este sitio web es un juego de adivinanzas satírico y educativo. No está afiliado a LinkedIn ni a Interpol. Todo el contenido es solo para fines de entretenimiento.",
        "backButton": "Volver al juego",
        "aboutButton": "Acerca de",
        "disclaimerButton": "Aviso Legal",
        "metaKeywords": "linkedin, interpol, juego, profesional, criminal, adivinar",
        "privacyTitle": "Política de Privacidad - LinkedIn o Interpol",
        "privacyHeaderV2": "Política de Privacidad",
        "privacyIntro": "Bienvenido a nuestro sitio web. Queremos que entiendas qué información recopilamos y cómo la usamos. Para mejorar este juego y mantenerlo gratuito, utilizamos servicios como Google Analytics.",
        "whatDataHeader": "¿Qué Información Recopilamos?",
        "whatDataText1": "Cuando utilizas nuestro sitio, recopilamos automáticamente cierta información para ayudarnos a entender a nuestra audiencia. Esto incluye:",
        "whatDataPoint1": "<b>Información General de Ubicación y Dispositivo:</b> Recopilamos datos como tu ciudad y el tipo de dispositivo que estás utilizando. Esto nos ayuda a saber de dónde son nuestros usuarios y cómo acceden al sitio.",
        "whatDataPoint2": "<b>Datos de Uso:</b> Vemos cómo interactúas con el juego, lo que nos ayuda a mejorar la experiencia del usuario.",
        "whatDataPoint3": "<b>Información de la Cuenta de Google:</b> Si has iniciado sesión en una cuenta de Google y tienes activada la personalización de anuncios, Google puede compartir con nosotros información demográfica anónima, como tu rango de edad o tus intereses. No recibimos ninguna información personal tuya, como tu nombre o correo electrónico.",
        "howDataHeader": "¿Cómo Utilizamos Esta Información?",
        "howDataText1": "Los datos que recopilamos nos ayudan a:",
        "howDataPoint1": "Mejorar y optimizar nuestro sitio web y juego.",
        "howDataPoint2": "Mostrarte anuncios que sean más relevantes para tus intereses.",
        "yourChoicesHeader": "Tus Datos y Tus Opciones",
        "yourChoicesText1": "Respetamos tu privacidad. Puedes controlar y gestionar la información que Google recopila sobre ti visitando la página <a href=\"https://myactivity.google.com/myactivity\" target=\"_blank\">Mi Actividad</a> de Google. Allí, puedes revisar y eliminar tus datos de actividad y ajustar la configuración de personalización de anuncios.",
        "yourConsentHeader": "Tu Consentimiento",
        "yourConsentText1": "Al utilizar nuestro sitio web, aceptas nuestra recopilación de datos y política de privacidad como se describe aquí.",
        "privacyButton": "Política de Privacidad",
        "learnMore": "Leer más",
        "cookieAccept": "¡Entendido!",
        "requestImageBtn": "Solicitar añadir una imagen",
        "requestImagePopupHeader": "Solicitar una nueva imagen",
        "requestImagePopupNameLabel": "Nombre:",
        "requestImagePopupLinkLabel": "Enlace de la imagen:",
        "requestImagePopupTypeLabel": "Tipo:",
        "requestImagePopupTypeLinkedin": "LinkedIn",
        "requestImagePopupTypeInterpol": "Interpol",
        "requestImagePopupSubmit": "Enviar solicitud",
        "structuredDataDescription": "Un divertido juego donde tienes que adivinar si una persona es un profesional de LinkedIn o un criminal de Interpol.",
        "structuredDataType": "Juego de deducción",
        "instructionsBtn": "Instrucciones",
        "instructionsPopupHeader": "Cómo Jugar",
        "instructionsPopupText1": "Se te mostrará una serie de imágenes.",
        "instructionsPopupText2": "Para cada imagen, debes adivinar si la persona es un profesional de LinkedIn o un criminal de Interpol.",
        "instructionsPopupText3": "Haz clic en el botón \"LinkedIn\" o \"Interpol\" para hacer tu suposición.",
        "instructionsPopupText4": "Tu puntuación se registra en la parte superior de la página.",
        "playButton": "Jugar"
    },
    "fr": {
        "title": "LinkedIn ou Interpol",
        "subtitle": "Professionnel ou Criminel? À vous de décider!",
        "score": "Score",
        "total": "Total",
        "autoAdvance": "Avance Automatique",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Image Suivante",
        "footerTitle": "LinkedIn ou Interpol - Un Jeu de Déduction - Version 1.0",
        "footerDisclaimer": "Avertissement: Ce site web est un jeu de devinettes satirique et éducatif.",
        "privacyPolicy": "Politique de Confidentialité",
        "termsOfService": "Conditions d'Utilisation",
        "copyright": "© 2025 Jan Queralt. Tous droits réservés.",
        "correct": "Correct!",
        "wrong": "Faux!",
        "policeRecord": "Dossier de Police",
        "imgDesc1": "Cette personne est sur LinkedIn.",
        "imgDesc2": "Iranien inculpé de piratage par le FBI.",
        "imgDesc3": "Cette personne est sur LinkedIn.",
        "imgDesc4": "Affaire de trafic et de distribution de drogue par le FBI.",
        "imgDesc5": "Cette personne est sur LinkedIn.",
        "imgDesc6": "Accusations de complot et d'agent étranger.",
        "imgDesc7": "Cette personne est sur LinkedIn.",
        "imgDesc8": "Kulkov inculpé de cybercriminalité.",
        "imgDesc9": "Cette personne est sur LinkedIn.",
        "imgDesc10": "Radovanovic accusé de complot de swatting.",
        "imgDesc11": "Cette personne est sur LinkedIn.",
        "imgDesc12": "Sokolov inculpé de fraude à la carte de crédit.",
        "imgDesc13": "Cette personne est sur LinkedIn.",
        "imgDesc14": "Complot de trafic de fentanyl et d'armes.",
        "imgDesc15": "Cette personne est sur LinkedIn.",
        "imgDesc16": "Accusations de complot pour distribution de drogue.",
        "imgDesc17": "Cette personne est sur LinkedIn.",
        "imgDesc18": "fait partie de l'organisation criminelle PSOE",
        "imgDesc19": "Cette personne est sur LinkedIn.",
        "imgDesc20": "Enlèvement d'enfant par Smrekar.",
        "imgDesc21": "Cette personne est sur LinkedIn.",
        "imgDesc22": "Mandats d'arrêt internationaux émis pour complot d'assassinat.",
        "imgDesc23": "Cette personne est sur LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO recherché pour vol de cocaïne.",
        "imgDesc25": "Cette personne est sur LinkedIn.",
        "imgDesc26": "recherché pour corruption à Taïwan.",
        "imgDesc27": "Cette personne est sur LinkedIn.",
        "imgDesc28": "Accusations de terrorisme et de cybercriminalité.",
        "imgDesc29": "Cette personne est sur LinkedIn.",
        "imgDesc30": "recherché pour meurtre et tentative de meurtre.",
        "imgDesc31": "Cette personne est sur LinkedIn.",
        "imgDesc32": "Lester Eubanks recherché pour meurtre et évasion.",
        "imgDesc33": "Cette personne est sur LinkedIn.",
        "imgDesc35": "Cette personne est sur LinkedIn.",
        "imgDesc37": "Cette personne est sur LinkedIn.",
        "imgDesc39": "Cette personne est sur LinkedIn.",
        "imgDesc41": "Cette personne est sur LinkedIn.",
        "imgDesc43": "Cette personne est sur LinkedIn.",
        "imgDesc45": "Cette personne est sur LinkedIn.",
        "imgDesc47": "Cette personne est sur LinkedIn.",
        "imgDesc49": "Cette personne est sur LinkedIn.",
        "professionalOrCriminal": "Professionnel ou Criminel?",
        "youDecide": "À vous de décider!",
        "aDeductionGame": "Un Jeu de Déduction",
        "version": "Version 1.0",
        "disclaimer": "Avertissement: Ce site web est un jeu de devinettes satirique et éducatif.",
        "allRightsReserved": "Tous droits réservés.",
        "metaDescription": "Un jeu amusant où vous devez deviner si une personne est un professionnel de LinkedIn ou un criminel d'Interpol.",
        "ogTitle": "LinkedIn ou Interpol",
        "ogDescription": "Un jeu amusant où vous devez deviner si une personne est un professionnel de LinkedIn ou un criminel d'Interpol.",
        "aboutTitle": "À propos - LinkedIn ou Interpol",
        "aboutHeader": "À propos du jeu",
        "aboutText": "Ce jeu a été créé à des fins de divertissement et d'éducation pour souligner les similitudes et les différences entre les profils professionnels et criminels. Toutes les images sont utilisées à des fins satiriques.",
        "disclaimerTitle": "Avis de non-responsabilité - LinkedIn ou Interpol",
        "disclaimerHeader": "Avis de non-responsabilité",
        "disclaimerText": "Ce site web est un jeu de devinettes satirique et éducatif. Il n'est affilié ni à LinkedIn ni à Interpol. Tout le contenu est uniquement à des fins de divertissement.",
        "backButton": "Retour au jeu",
        "aboutButton": "À propos",
        "disclaimerButton": "Avis",
        "metaKeywords": "linkedin, interpol, jeu, professionnel, criminel, deviner",
        "privacyTitle": "Politique de Confidentialité - LinkedIn ou Interpol",
        "privacyHeaderV2": "Politique de Confidentialité",
        "privacyIntro": "Bienvenue sur notre site. Nous voulons que vous compreniez quelles informations nous collectons et comment nous les utilisons. Pour améliorer ce jeu et le maintenir gratuit, nous utilisons des services comme Google Analytics.",
        "whatDataHeader": "Quelles Informations Collectons-Nous?",
        "whatDataText1": "Lorsque vous utilisez notre site, nous collectons automatiquement certaines informations pour nous aider à comprendre notre public. Cela inclut:",
        "whatDataPoint1": "<b>Informations Générales sur la Localisation et l'Appareil:</b> Nous collectons des données comme votre ville et le type d'appareil que vous utilisez. Cela nous aide à savoir d'où viennent nos utilisateurs et comment ils accèdent au site.",
        "whatDataPoint2": "<b>Données d'Utilisation:</b> Nous voyons comment vous interagissez avec le jeu, ce qui nous aide à améliorer l'expérience utilisateur.",
        "whatDataPoint3": "<b>Informations sur le Compte Google:</b> Si vous êtes connecté à un compte Google et avez activé la personnalisation des annonces, Google peut partager avec nous des informations démographiques anonymes, telles que votre tranche d'âge ou vos centres d'intérêt. Nous ne recevons aucune de vos informations personnelles, comme votre nom ou votre e-mail.",
        "howDataHeader": "Comment Utilisons-Nous Ces Informations?",
        "howDataText1": "Les données que nous collectons nous aident à:",
        "howDataPoint1": "Améliorer et optimiser notre site web et notre jeu.",
        "howDataPoint2": "Vous montrer des publicités plus pertinentes pour vos centres d'intérêt.",
        "yourChoicesHeader": "Vos Données et Vos Choix",
        "yourChoicesText1": "Nous respectons votre vie privée. Vous pouvez contrôler et gérer les informations que Google collecte à votre sujet en visitant la page <a href=\"https://myactivity.google.com/myactivity\" target=\"_blank\">Mon Activité</a> de Google. Là, vous pouvez consulter et supprimer vos données d'activité et ajuster vos paramètres de personnalisation des annonces.",
        "yourConsentHeader": "Votre Consentement",
        "yourConsentText1": "En utilisant notre site web, vous consentez à notre collecte de données et à notre politique de confidentialité telles que décrites ici.",
        "privacyButton": "Politique de Confidentialité",
        "learnMore": "En savoir plus",
        "cookieAccept": "J'ai compris!",
        "requestImageBtn": "Demander l'ajout d'une image",
        "requestImagePopupHeader": "Demander une nouvelle image",
        "requestImagePopupNameLabel": "Nom:",
        "requestImagePopupLinkLabel": "Lien de l'image:",
        "requestImagePopupTypeLabel": "Type:",
        "requestImagePopupTypeLinkedin": "LinkedIn",
        "requestImagePopupTypeInterpol": "Interpol",
        "requestImagePopupSubmit": "Envoyer la demande",
        "instructionsBtn": "Instructions",
        "instructionsPopupHeader": "Comment Jouer",
        "instructionsPopupText1": "Une série d'images vous sera présentée.",
        "instructionsPopupText2": "Pour chaque image, vous devez deviner si la personne est un professionnel de LinkedIn ou un criminel d'Interpol.",
        "instructionsPopupText3": "Cliquez sur le bouton \"LinkedIn\" ou \"Interpol\" pour faire votre supposition.",
        "instructionsPopupText4": "Votre score est suivi en haut de la page.",
        "playButton": "Jouer"
    },
    "de": {
        "title": "LinkedIn oder Interpol",
        "subtitle": "Profi oder Verbrecher? Du entscheidest!",
        "score": "Punktzahl",
        "total": "Gesamt",
        "autoAdvance": "Automatischer Vorlauf",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Nächstes Bild",
        "footerTitle": "LinkedIn oder Interpol - Ein Deduktionsspiel - Version 1.0",
        "footerDisclaimer": "Haftungsausschluss: Diese Website ist ein satirisches und lehrreiches Ratespiel.",
        "privacyPolicy": "Datenschutzrichtlinie",
        "termsOfService": "Nutzungsbedingungen",
        "copyright": "© 2025 Jan Queralt. Alle Rechte vorbehalten.",
        "correct": "Richtig!",
        "wrong": "Falsch!",
        "policeRecord": "Polizeiakte",
        "imgDesc1": "Diese Person ist auf LinkedIn.",
        "imgDesc2": "Iraner vom FBI des Hackens angeklagt.",
        "imgDesc3": "Diese Person ist auf LinkedIn.",
        "imgDesc4": "Fall von Drogenhandel und -verteilung durch das FBI.",
        "imgDesc5": "Diese Person ist auf LinkedIn.",
        "imgDesc6": "Anklage wegen Verschwörung und Agententätigkeit für eine ausländische Macht.",
        "imgDesc7": "Diese Person ist auf LinkedIn.",
        "imgDesc8": "Kulkov wegen Cyberkriminalität angeklagt.",
        "imgDesc9": "Diese Person ist auf LinkedIn.",
        "imgDesc10": "Radovanovic wegen Swatting-Verschwörung angeklagt.",
        "imgDesc11": "Diese Person ist auf LinkedIn.",
        "imgDesc12": "Sokolov wegen Kreditkartenbetrugs angeklagt.",
        "imgDesc13": "Diese Person ist auf LinkedIn.",
        "imgDesc14": "Verschwörung zum Handel mit Fentanyl und Waffen.",
        "imgDesc15": "Diese Person ist auf LinkedIn.",
        "imgDesc16": "Anklage wegen Verschwörung zum Drogenhandel.",
        "imgDesc17": "Diese Person ist auf LinkedIn.",
        "imgDesc18": "ist Teil der kriminellen Organisation PSOE",
        "imgDesc19": "Diese Person ist auf LinkedIn.",
        "imgDesc20": "Kindesentführung durch Smrekar.",
        "imgDesc21": "Diese Person ist auf LinkedIn.",
        "imgDesc22": "Internationale Haftbefehle wegen Mordkomplotts erlassen.",
        "imgDesc23": "Diese Person ist auf LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO wegen Kokainraubs gesucht.",
        "imgDesc25": "Diese Person ist auf LinkedIn.",
        "imgDesc26": "wegen Korruption in Taiwan gesucht.",
        "imgDesc27": "Diese Person ist auf LinkedIn.",
        "imgDesc28": "Anklage wegen Terrorismus und Cyberkriminalität.",
        "imgDesc29": "Diese Person ist auf LinkedIn.",
        "imgDesc30": "wegen Mordes und versuchten Mordes gesucht.",
        "imgDesc31": "Diese Person ist auf LinkedIn.",
        "imgDesc32": "Lester Eubanks wegen Mordes und Flucht gesucht.",
        "imgDesc33": "Diese Person ist auf LinkedIn.",
        "imgDesc35": "Diese Person ist auf LinkedIn.",
        "imgDesc37": "Diese Person ist auf LinkedIn.",
        "imgDesc39": "Diese Person ist auf LinkedIn.",
        "imgDesc41": "Diese Person ist auf LinkedIn.",
        "imgDesc43": "Diese Person ist auf LinkedIn.",
        "imgDesc45": "Diese Person ist auf LinkedIn.",
        "imgDesc47": "Diese Person ist auf LinkedIn.",
        "imgDesc49": "Diese Person ist auf LinkedIn.",
        "professionalOrCriminal": "Profi oder Verbrecher?",
        "youDecide": "Du entscheidest!",
        "aDeductionGame": "Ein Deduktionsspiel",
        "version": "Version 1.0",
        "disclaimer": "Haftungsausschluss: Diese Website ist ein satirisches und lehrreiches Ratespiel.",
        "allRightsReserved": "Alle Rechte vorbehalten.",
        "metaDescription": "Ein lustiges Spiel, bei dem du erraten musst, ob eine Person ein LinkedIn-Profi oder ein Interpol-Verbrecher ist.",
        "ogTitle": "LinkedIn oder Interpol",
        "ogDescription": "Ein lustiges Spiel, bei dem du erraten musst, ob eine Person ein LinkedIn-Profi oder ein Interpol-Verbrecher ist.",
        "aboutTitle": "Über - LinkedIn oder Interpol",
        "aboutHeader": "Über das Spiel",
        "aboutText": "Dieses Spiel wurde zu Unterhaltungs- und Bildungszwecken erstellt, um die Ähnlichkeiten und Unterschiede in Berufs- und Kriminellenprofilen aufzuzeigen. Alle Bilder werden zu satirischen Zwecken verwendet.",
        "disclaimerTitle": "Haftungsausschluss - LinkedIn oder Interpol",
        "disclaimerHeader": "Haftungsausschluss",
        "disclaimerText": "Diese Website ist ein satirisches und lehrreiches Ratespiel. Sie ist nicht mit LinkedIn oder Interpol verbunden. Alle Inhalte dienen nur zu Unterhaltungszwecken.",
        "backButton": "Zurück zum Spiel",
        "aboutButton": "Über",
        "disclaimerButton": "Haftungsausschluss",
        "metaKeywords": "linkedin, interpol, spiel, profi, verbrecher, raten",
        "privacyTitle": "Datenschutzrichtlinie - LinkedIn oder Interpol",
        "privacyHeaderV2": "Datenschutzrichtlinie",
        "privacyIntro": "Willkommen auf unserer Website. Wir möchten, dass Sie verstehen, welche Informationen wir sammeln und wie wir sie verwenden. Um dieses Spiel zu verbessern und kostenlos zu halten, nutzen wir Dienste wie Google Analytics.",
        "whatDataHeader": "Welche Informationen sammeln wir?",
        "whatDataText1": "Wenn Sie unsere Website nutzen, sammeln wir automatisch einige Informationen, um unser Publikum besser zu verstehen. Dazu gehören:",
        "whatDataPoint1": "<b>Allgemeine Standort- und Geräteinformationen:</b> Wir sammeln Daten wie Ihre Stadt und den Typ des von Ihnen verwendeten Geräts. Dies hilft uns zu wissen, woher unsere Benutzer kommen und wie sie auf die Website zugreifen.",
        "whatDataPoint2": "<b>Nutzungsdaten:</b> Wir sehen, wie Sie mit dem Spiel interagieren, was uns hilft, die Benutzererfahrung zu verbessern.",
        "whatDataPoint3": "<b>Google-Kontoinformationen:</b> Wenn Sie in einem Google-Konto angemeldet sind und die Anzeigenpersonalisierung aktiviert haben, kann Google anonyme demografische Informationen wie Ihre Altersgruppe oder Interessen mit uns teilen. Wir erhalten keine Ihrer persönlichen Informationen wie Ihren Namen oder Ihre E-Mail-Adresse.",
        "howDataHeader": "Wie verwenden wir diese Informationen?",
        "howDataText1": "Die von uns gesammelten Daten helfen uns dabei:",
        "howDataPoint1": "Unsere Website und unser Spiel zu verbessern und zu optimieren.",
        "howDataPoint2": "Ihnen Anzeigen zu zeigen, die für Ihre Interessen relevanter sind.",
        "yourChoicesHeader": "Ihre Daten und Ihre Wahlmöglichkeiten",
        "yourChoicesText1": "Wir respektieren Ihre Privatsphäre. Sie können die von Google über Sie gesammelten Informationen kontrollieren und verwalten, indem Sie die Seite <a href=\"https://myactivity.google.com/myactivity\" target=\"_blank\">Meine Aktivität</a> von Google besuchen. Dort können Sie Ihre Aktivitätsdaten überprüfen und löschen sowie Ihre Einstellungen zur Anzeigenpersonalisierung anpassen.",
        "yourConsentHeader": "Ihre Zustimmung",
        "yourConsentText1": "Durch die Nutzung unserer Website stimmen Sie unserer Datenerfassung und Datenschutzrichtlinie wie hier beschrieben zu.",
        "privacyButton": "Datenschutzrichtlinie",
        "learnMore": "Mehr erfahren",
        "cookieAccept": "Verstanden!",
        "requestImageBtn": "Bild hinzufügen anfordern",
        "requestImagePopupHeader": "Neues Bild anfordern",
        "requestImagePopupNameLabel": "Name:",
        "requestImagePopupLinkLabel": "Bildlink:",
        "requestImagePopupTypeLabel": "Typ:",
        "requestImagePopupTypeLinkedin": "LinkedIn",
        "requestImagePopupTypeInterpol": "Interpol",
        "requestImagePopupSubmit": "Anfrage senden",
        "instructionsBtn": "Anleitung",
        "instructionsPopupHeader": "Spielanleitung",
        "instructionsPopupText1": "Ihnen wird eine Reihe von Bildern gezeigt.",
        "instructionsPopupText2": "Für jedes Bild müssen Sie raten, ob die Person ein Profi von LinkedIn oder ein Krimineller von Interpol ist.",
        "instructionsPopupText3": "Klicken Sie auf die Schaltfläche \"LinkedIn\" oder \"Interpol\", um Ihre Vermutung abzugeben.",
        "instructionsPopupText4": "Ihre Punktzahl wird oben auf der Seite verfolgt.",
        "playButton": "Spielen"
    },
    "pt": {
        "title": "LinkedIn ou Interpol",
        "subtitle": "Profissional ou Criminoso? Você decide!",
        "score": "Pontuação",
        "total": "Total",
        "autoAdvance": "Avanço Automático",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Próxima Imagem",
        "footerTitle": "LinkedIn ou Interpol - Um Jogo de Dedução - Versão 1.0",
        "footerDisclaimer": "Aviso: Este site é um jogo de adivinhação satírico e educacional.",
        "privacyPolicy": "Política de Privacidade",
        "termsOfService": "Termos de Serviço",
        "copyright": "© 2025 Jan Queralt. Todos os direitos reservados.",
        "correct": "Correto!",
        "wrong": "Errado!",
        "policeRecord": "Ficha Criminal",
        "imgDesc1": "Esta pessoa está no LinkedIn.",
        "imgDesc2": "Iraniano indiciado por hacking pelo FBI.",
        "imgDesc3": "Esta pessoa está no LinkedIn.",
        "imgDesc4": "Caso de tráfico e distribuição de drogas pelo FBI.",
        "imgDesc5": "Esta pessoa está no LinkedIn.",
        "imgDesc6": "Acusações de conspiração e agente estrangeiro.",
        "imgDesc7": "Esta pessoa está no LinkedIn.",
        "imgDesc8": "Kulkov indiciado por cibercrime.",
        "imgDesc9": "Esta pessoa está no LinkedIn.",
        "imgDesc10": "Radovanovic acusado de conspiração de swatting.",
        "imgDesc11": "Esta pessoa está no LinkedIn.",
        "imgDesc12": "Sokolov indiciado por fraude de cartão de crédito.",
        "imgDesc13": "Esta pessoa está no LinkedIn.",
        "imgDesc14": "Conspiração de tráfico de fentanil e armas.",
        "imgDesc15": "Esta pessoa está no LinkedIn.",
        "imgDesc16": "Acusações de conspiração para distribuição de drogas.",
        "imgDesc17": "Esta pessoa está no LinkedIn.",
        "imgDesc18": "faz parte da organização criminosa PSOE",
        "imgDesc19": "Esta pessoa está no LinkedIn.",
        "imgDesc20": "Rapto de criança por Smrekar.",
        "imgDesc21": "Esta pessoa está no LinkedIn.",
        "imgDesc22": "Mandados de prisão internacionais emitidos por conspiração para assassinato.",
        "imgDesc23": "Esta pessoa está no LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO procurado por roubo de cocaína.",
        "imgDesc25": "Esta pessoa está no LinkedIn.",
        "imgDesc26": "procurado por corrupção em Taiwan.",
        "imgDesc27": "Esta pessoa está no LinkedIn.",
        "imgDesc28": "Acusações de terrorismo e cibercrime.",
        "imgDesc29": "Esta pessoa está no LinkedIn.",
        "imgDesc30": "procurado por homicídio e tentativa de homicídio.",
        "imgDesc31": "Esta pessoa está no LinkedIn.",
        "imgDesc32": "Lester Eubanks procurado por homicídio e fuga.",
        "imgDesc33": "Esta pessoa está no LinkedIn.",
        "imgDesc35": "Esta pessoa está no LinkedIn.",
        "imgDesc37": "Esta pessoa está no LinkedIn.",
        "imgDesc39": "Esta pessoa está no LinkedIn.",
        "imgDesc41": "Esta pessoa está no LinkedIn.",
        "imgDesc43": "Esta pessoa está no LinkedIn.",
        "imgDesc45": "Esta pessoa está no LinkedIn.",
        "imgDesc47": "Esta pessoa está no LinkedIn.",
        "imgDesc49": "Esta pessoa está no LinkedIn.",
        "professionalOrCriminal": "Profissional ou Criminoso?",
        "youDecide": "Você decide!",
        "aDeductionGame": "Um Jogo de Dedução",
        "version": "Versão 1.0",
        "disclaimer": "Aviso: Este site é um jogo de adivinhação satírico e educacional.",
        "allRightsReserved": "Todos os direitos reservados.",
        "metaDescription": "Um jogo divertido onde você tem que adivinhar se uma pessoa é um profissional do LinkedIn ou um criminoso da Interpol.",
        "ogTitle": "LinkedIn ou Interpol",
        "ogDescription": "Um jogo divertido onde você tem que adivinhar se uma pessoa é um profissional do LinkedIn ou um criminoso da Interpol.",
        "aboutTitle": "Sobre - LinkedIn ou Interpol",
        "aboutHeader": "Sobre o Jogo",
        "aboutText": "Este jogo foi criado para fins de entretenimento e educacionais para destacar as semelhanças e diferenças nos perfis profissionais e criminosos. Todas as imagens são usadas para fins satíricos.",
        "disclaimerTitle": "Aviso Legal - LinkedIn ou Interpol",
        "disclaimerHeader": "Aviso Legal",
        "disclaimerText": "Este site é um jogo de adivinhação satírico e educacional. Não é afiliado ao LinkedIn ou à Interpol. Todo o conteúdo é apenas para fins de entretenimento.",
        "backButton": "Voltar ao jogo",
        "aboutButton": "Sobre",
        "disclaimerButton": "Aviso Legal",
        "metaKeywords": "linkedin, interpol, jogo, profissional, criminoso, adivinhar",
        "privacyTitle": "Política de Privacidade - LinkedIn ou Interpol",
        "privacyHeaderV2": "Política de Privacidade",
        "privacyIntro": "Bem-vindo ao nosso site. Queremos que você entenda quais informações coletamos e como as usamos. Para melhorar este jogo e mantê-lo gratuito, usamos serviços como o Google Analytics.",
        "whatDataHeader": "Quais Informações Coletamos?",
        "whatDataText1": "Quando você usa nosso site, coletamos automaticamente algumas informações para nos ajudar a entender nosso público. Isso inclui:",
        "whatDataPoint1": "<b>Informações Gerais de Localização e Dispositivo:</b> Coletamos dados como sua cidade e o tipo de dispositivo que você está usando. Isso nos ajuda a saber de onde são nossos usuários e como eles acessam o site.",
        "whatDataPoint2": "<b>Dados de Uso:</b> Vemos como você interage com o jogo, o que nos ajuda a melhorar a experiência do usuário.",
        "whatDataPoint3": "<b>Informações da Conta do Google:</b> Se você estiver conectado a uma conta do Google e tiver a personalização de anúncios ativada, o Google poderá compartilhar conosco informações demográficas anônimas, como sua faixa etária ou interesses. Não recebemos nenhuma de suas informações pessoais, como seu nome ou e-mail.",
        "howDataHeader": "Como Usamos Essas Informações?",
        "howDataText1": "Os dados que coletamos nos ajudam a:",
        "howDataPoint1": "Melhorar e otimizar nosso site e jogo.",
        "howDataPoint2": "Mostrar anúncios mais relevantes para seus interesses.",
        "yourChoicesHeader": "Seus Dados e Suas Escolhas",
        "yourChoicesText1": "Respeitamos sua privacidade. Você pode controlar e gerenciar as informações que o Google coleta sobre você visitando a página <a href=\"https://myactivity.google.com/myactivity\" target=\"_blank\">Minha Atividade</a> do Google. Lá, você pode revisar e excluir seus dados de atividade e ajustar suas configurações de personalização de anúncios.",
        "yourConsentHeader": "Seu Consentimento",
        "yourConsentText1": "Ao usar nosso site, você concorda com nossa coleta de dados e política de privacidade, conforme descrito aqui.",
        "privacyButton": "Política de Privacidade",
        "learnMore": "Saiba mais",
        "cookieAccept": "Entendi!",
        "requestImageBtn": "Solicitar a adição de uma imagem",
        "requestImagePopupHeader": "Solicitar uma nova imagem",
        "requestImagePopupNameLabel": "Nome:",
        "requestImagePopupLinkLabel": "Link da imagem:",
        "requestImagePopupTypeLabel": "Tipo:",
        "requestImagePopupTypeLinkedin": "LinkedIn",
        "requestImagePopupTypeInterpol": "Interpol",
        "requestImagePopupSubmit": "Enviar solicitação",
        "instructionsBtn": "Instruções",
        "instructionsPopupHeader": "Como Jogar",
        "instructionsPopupText1": "Você verá uma série de imagens.",
        "instructionsPopupText2": "Para cada imagem, você deve adivinhar se a pessoa é um profissional do LinkedIn ou um criminoso da Interpol.",
        "instructionsPopupText3": "Clique no botão \"LinkedIn\" ou \"Interpol\" para fazer sua suposição.",
        "instructionsPopupText4": "Sua pontuação é acompanhada no topo da página.",
        "playButton": "Jogar"
    },
    "it": {
        "title": "LinkedIn o Interpol",
        "subtitle": "Professionista o Criminale? Tu decidi!",
        "score": "Punteggio",
        "total": "Totale",
        "autoAdvance": "Avanzamento Automatico",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Immagine Successiva",
        "footerTitle": "LinkedIn o Interpol - Un Gioco di Deduzione - Versione 1.0",
        "footerDisclaimer": "Disclaimer: Questo sito web è un gioco di indovinelli satirico ed educativo.",
        "privacyPolicy": "Informativa sulla Privacy",
        "termsOfService": "Termini di Servizio",
        "copyright": "© 2025 Jan Queralt. Tutti i diritti riservati.",
        "correct": "Corretto!",
        "wrong": "Sbagliato!",
        "policeRecord": "Precedenti Penali",
        "imgDesc1": "Questa persona è su LinkedIn.",
        "imgDesc2": "Iraniano incriminato per hacking dall'FBI.",
        "imgDesc3": "Questa persona è su LinkedIn.",
        "imgDesc4": "Caso di traffico e distribuzione di droga dall'FBI.",
        "imgDesc5": "Questa persona è su LinkedIn.",
        "imgDesc6": "Accuse di cospirazione e agente straniero.",
        "imgDesc7": "Questa persona è su LinkedIn.",
        "imgDesc8": "Kulkov incriminato per cybercrime.",
        "imgDesc9": "Questa persona è su LinkedIn.",
        "imgDesc10": "Radovanovic accusato di cospirazione per swatting.",
        "imgDesc11": "Questa persona è su LinkedIn.",
        "imgDesc12": "Sokolov incriminato per frode con carta di credito.",
        "imgDesc13": "Questa persona è su LinkedIn.",
        "imgDesc14": "Cospirazione per il traffico di fentanil e armi.",
        "imgDesc15": "Questa persona è su LinkedIn.",
        "imgDesc16": "Accuse di cospirazione per la distribuzione di droga.",
        "imgDesc17": "Questa persona è su LinkedIn.",
        "imgDesc18": "fa parte dell'organizzazione criminale PSOE",
        "imgDesc19": "Questa persona è su LinkedIn.",
        "imgDesc20": "Rapimento di minore da parte di Smrekar.",
        "imgDesc21": "Questa persona è su LinkedIn.",
        "imgDesc22": "Mandati di arresto internazionali emessi per complotto di omicidio.",
        "imgDesc23": "Questa persona è su LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO ricercato per rapina di cocaina.",
        "imgDesc25": "Questa persona è su LinkedIn.",
        "imgDesc26": "ricercato per corruzione a Taiwan.",
        "imgDesc27": "Questa persona è su LinkedIn.",
        "imgDesc28": "Accuse di terrorismo e cybercrime.",
        "imgDesc29": "Questa persona è su LinkedIn.",
        "imgDesc30": "ricercato per omicidio e tentato omicidio.",
        "imgDesc31": "Questa persona è su LinkedIn.",
        "imgDesc32": "Lester Eubanks ricercato per omicidio ed evasione.",
        "imgDesc33": "Questa persona è su LinkedIn.",
        "imgDesc35": "Questa persona è su LinkedIn.",
        "imgDesc37": "Questa persona è su LinkedIn.",
        "imgDesc39": "Questa persona è su LinkedIn.",
        "imgDesc41": "Questa persona è su LinkedIn.",
        "imgDesc43": "Questa persona è su LinkedIn.",
        "imgDesc45": "Questa persona è su LinkedIn.",
        "imgDesc47": "Questa persona è su LinkedIn.",
        "imgDesc49": "Questa persona è su LinkedIn.",
        "professionalOrCriminal": "Professionista o Criminale?",
        "youDecide": "Tu decidi!",
        "aDeductionGame": "Un Gioco di Deduzione",
        "version": "Versione 1.0",
        "disclaimer": "Disclaimer: Questo sito web è un gioco di indovinelli satirico ed educativo.",
        "allRightsReserved": "Tutti i diritti riservati.",
        "metaDescription": "Un gioco divertente in cui devi indovinare se una persona è un professionista di LinkedIn o un criminale dell'Interpol.",
        "ogTitle": "LinkedIn o Interpol",
        "ogDescription": "Un gioco divertente in cui devi indovinare se una persona è un professionista di LinkedIn o un criminale dell'Interpol.",
        "aboutTitle": "Informazioni - LinkedIn o Interpol",
        "aboutHeader": "Informazioni sul Gioco",
        "aboutText": "Questo gioco è stato creato per scopi di intrattenimento ed educativi per evidenziare le somiglianze e le differenze nei profili professionali e criminali. Tutte le immagini sono utilizzate a scopo satirico.",
        "disclaimerTitle": "Disclaimer - LinkedIn o Interpol",
        "disclaimerHeader": "Disclaimer",
        "disclaimerText": "Questo sito web è un gioco di indovinelli satirico ed educativo. Non è affiliato a LinkedIn o Interpol. Tutti i contenuti sono solo a scopo di intrattenimento.",
        "backButton": "Torna al gioco",
        "aboutButton": "Informazioni",
        "disclaimerButton": "Disclaimer",
        "metaKeywords": "linkedin, interpol, gioco, professionista, criminale, indovinare",
        "privacyTitle": "Informativa sulla Privacy - LinkedIn o Interpol",
        "privacyHeaderV2": "Informativa sulla Privacy",
        "privacyIntro": "Benvenuti nel nostro sito. Vogliamo che capiate quali informazioni raccogliamo e come le usiamo. Per migliorare questo gioco e mantenerlo gratuito, utilizziamo servizi come Google Analytics.",
        "whatDataHeader": "Quali Informazioni Raccogliamo?",
        "whatDataText1": "Quando utilizzate il nostro sito, raccogliamo automaticamente alcune informazioni per aiutarci a capire il nostro pubblico. Queste includono:",
        "whatDataPoint1": "<b>Informazioni Generali su Posizione e Dispositivo:</b> Raccogliamo dati come la vostra città e il tipo di dispositivo che state utilizzando. Questo ci aiuta a sapere da dove provengono i nostri utenti e come accedono al sito.",
        "whatDataPoint2": "<b>Dati di Utilizzo:</b> Vediamo come interagite con il gioco, il che ci aiuta a migliorare l'esperienza dell'utente.",
        "whatDataPoint3": "<b>Informazioni sull'Account Google:</b> Se siete connessi a un account Google e avete attivato la personalizzazione degli annunci, Google potrebbe condividere con noi informazioni demografiche anonime, come la vostra fascia d'età o i vostri interessi. Non riceviamo alcuna vostra informazione personale, come il vostro nome o la vostra email.",
        "howDataHeader": "Come Utilizziamo Queste Informazioni?",
        "howDataText1": "I dati che raccogliamo ci aiutano a:",
        "howDataPoint1": "Migliorare e ottimizzare il nostro sito web e il nostro gioco.",
        "howDataPoint2": "Mostrare annunci più pertinenti ai vostri interessi.",
        "yourChoicesHeader": "I Vostri Dati e le Vostre Scelte",
        "yourChoicesText1": "Rispettiamo la vostra privacy. Potete controllare e gestire le informazioni che Google raccoglie su di voi visitando la pagina <a href=\"https://myactivity.google.com/myactivity\" target=\"_blank\">Le mie attività</a> di Google. Lì potete rivedere ed eliminare i vostri dati di attività e modificare le impostazioni di personalizzazione degli annunci.",
        "yourConsentHeader": "Il Vostro Consenso",
        "yourConsentText1": "Utilizzando il nostro sito web, acconsentite alla nostra raccolta di dati e alla nostra politica sulla privacy come descritto qui.",
        "privacyButton": "Informativa sulla Privacy",
        "learnMore": "Scopri di più",
        "cookieAccept": "Ho capito!",
        "requestImageBtn": "Richiedi di aggiungere un'immagine",
        "requestImagePopupHeader": "Richiedi una nuova immagine",
        "requestImagePopupNameLabel": "Nome:",
        "requestImagePopupLinkLabel": "Link immagine:",
        "requestImagePopupTypeLabel": "Tipo:",
        "requestImagePopupTypeLinkedin": "LinkedIn",
        "requestImagePopupTypeInterpol": "Interpol",
        "requestImagePopupSubmit": "Invia richiesta",
        "instructionsBtn": "Istruzioni",
        "instructionsPopupHeader": "Come Giocare",
        "instructionsPopupText1": "Ti verrà mostrata una serie di immagini.",
        "instructionsPopupText2": "Per ogni immagine, devi indovinare se la persona è un professionista di LinkedIn o un criminale dell'Interpol.",
        "instructionsPopupText3": "Clicca sul pulsante \"LinkedIn\" o \"Interpol\" per fare la tua ipotesi.",
        "instructionsPopupText4": "Il tuo punteggio è tracciato in cima alla pagina.",
        "playButton": "Gioca"
    },
    "nl": {
        "title": "LinkedIn of Interpol",
        "subtitle": "Professional of Crimineel? Jij beslist!",
        "score": "Score",
        "total": "Totaal",
        "autoAdvance": "Automatisch Doorgaan",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Volgende Afbeelding",
        "footerTitle": "LinkedIn of Interpol - Een Deductiespel - Versie 1.0",
        "footerDisclaimer": "Disclaimer: Deze website is een satirisch en educatief raadspel.",
        "privacyPolicy": "Privacybeleid",
        "termsOfService": "Servicevoorwaarden",
        "copyright": "© 2025 Jan Queralt. Alle rechten voorbehouden.",
        "correct": "Correct!",
        "wrong": "Fout!",
        "policeRecord": "Politierapport",
        "imgDesc1": "Deze persoon staat op LinkedIn.",
        "imgDesc2": "Iraniër aangeklaagd voor hacken door de FBI.",
        "imgDesc3": "Deze persoon staat op LinkedIn.",
        "imgDesc4": "Zaak van drugshandel en -distributie door de FBI.",
        "imgDesc5": "Deze persoon staat op LinkedIn.",
        "imgDesc6": "Aanklacht wegens samenzwering en buitenlandse agent.",
        "imgDesc7": "Deze persoon staat op LinkedIn.",
        "imgDesc8": "Kulkov aangeklaagd voor cybercriminaliteit.",
        "imgDesc9": "Deze persoon staat op LinkedIn.",
        "imgDesc10": "Radovanovic beschuldigd van swatting-samenzwering.",
        "imgDesc11": "Deze persoon staat op LinkedIn.",
        "imgDesc12": "Sokolov aangeklaagd voor creditcardfraude.",
        "imgDesc13": "Deze persoon staat op LinkedIn.",
        "imgDesc14": "Samenzwering voor de handel in fentanyl en wapens.",
        "imgDesc15": "Deze persoon staat op LinkedIn.",
        "imgDesc16": "Aanklacht wegens samenzwering voor drugshandel.",
        "imgDesc17": "Deze persoon staat op LinkedIn.",
        "imgDesc18": "maakt deel uit van de criminele organisatie PSOE",
        "imgDesc19": "Deze persoon staat op LinkedIn.",
        "imgDesc20": "Kinderontvoering door Smrekar.",
        "imgDesc21": "Deze persoon staat op LinkedIn.",
        "imgDesc22": "Internationale arrestatiebevelen uitgevaardigd voor moordcomplot.",
        "imgDesc23": "Deze persoon staat op LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO gezocht voor cocaïneroof.",
        "imgDesc25": "Deze persoon staat op LinkedIn.",
        "imgDesc26": "gezocht voor corruptie in Taiwan.",
        "imgDesc27": "Deze persoon staat op LinkedIn.",
        "imgDesc28": "Aanklacht wegens terrorisme en cybercriminaliteit.",
        "imgDesc29": "Deze persoon staat op LinkedIn.",
        "imgDesc30": "gezocht voor moord en poging tot moord.",
        "imgDesc31": "Deze persoon staat op LinkedIn.",
        "imgDesc32": "Lester Eubanks gezocht voor moord en ontsnapping.",
        "imgDesc33": "Deze persoon staat op LinkedIn.",
        "imgDesc35": "Deze persoon staat op LinkedIn.",
        "imgDesc37": "Deze persoon staat op LinkedIn.",
        "imgDesc39": "Deze persoon staat op LinkedIn.",
        "imgDesc41": "Deze persoon staat op LinkedIn.",
        "imgDesc43": "Deze persoon staat op LinkedIn.",
        "imgDesc45": "Deze persoon staat op LinkedIn.",
        "imgDesc47": "Deze persoon staat op LinkedIn.",
        "imgDesc49": "Deze persoon staat op LinkedIn.",
        "professionalOrCriminal": "Professional of Crimineel?",
        "youDecide": "Jij beslist!",
        "aDeductionGame": "Een Deductiespel",
        "version": "Versie 1.0",
        "disclaimer": "Disclaimer: Deze website is een satirisch en educatief raadspel.",
        "allRightsReserved": "Alle rechten voorbehouden.",
        "metaDescription": "Een leuk spel waarbij je moet raden of een persoon een LinkedIn-professional of een Interpol-crimineel is.",
        "ogTitle": "LinkedIn of Interpol",
        "ogDescription": "Een leuk spel waarbij je moet raden of een persoon een LinkedIn-professional of een Interpol-crimineel is.",
        "aboutTitle": "Over - LinkedIn of Interpol",
        "aboutHeader": "Over het Spel",
        "aboutText": "Dit spel is gemaakt voor amusements- en educatieve doeleinden om de overeenkomsten en verschillen in professionele en criminele profielen te benadrukken. Alle afbeeldingen worden gebruikt voor satirische doeleinden.",
        "disclaimerTitle": "Disclaimer - LinkedIn of Interpol",
        "disclaimerHeader": "Disclaimer",
        "disclaimerText": "Deze website is een satirisch en educatief raadspel. Het is niet gelieerd aan LinkedIn of Interpol. Alle inhoud is uitsluitend voor amusementsdoeleinden.",
        "backButton": "Terug naar het spel",
        "aboutButton": "Over",
        "disclaimerButton": "Disclaimer",
        "metaKeywords": "linkedin, interpol, spel, professional, crimineel, raden",
        "privacyTitle": "Privacybeleid - LinkedIn of Interpol",
        "privacyHeaderV2": "Privacybeleid",
        "privacyIntro": "Welkom op onze website. We willen dat u begrijpt welke informatie we verzamelen en hoe we die gebruiken. Om dit spel te verbeteren en gratis te houden, gebruiken we diensten zoals Google Analytics.",
        "whatDataHeader": "Welke Informatie Verzamelen We?",
        "whatDataText1": "Wanneer u onze site gebruikt, verzamelen we automatisch bepaalde informatie om ons publiek beter te begrijpen. Dit omvat:",
        "whatDataPoint1": "<b>Algemene Locatie- en Apparaatinformatie:</b> We verzamelen gegevens zoals uw stad en het type apparaat dat u gebruikt. Dit helpt ons te weten waar onze gebruikers vandaan komen en hoe ze de site bezoeken.",
        "whatDataPoint2": "<b>Gebruiksgegevens:</b> We zien hoe u met het spel omgaat, wat ons helpt de gebruikerservaring te verbeteren.",
        "whatDataPoint3": "<b>Google-accountinformatie:</b> Als u bent ingelogd op een Google-account en advertentiepersonalisatie hebt ingeschakeld, kan Google anonieme demografische informatie met ons delen, zoals uw leeftijdscategorie of interesses. We ontvangen geen van uw persoonlijke gegevens, zoals uw naam of e-mailadres.",
        "howDataHeader": "Hoe Gebruiken We Deze Informatie?",
        "howDataText1": "De gegevens die we verzamelen, helpen ons om:",
        "howDataPoint1": "Onze website en ons spel te verbeteren en te optimaliseren.",
        "howDataPoint2": "U advertenties te tonen die relevanter zijn voor uw interesses.",
        "yourChoicesHeader": "Uw Gegevens en Uw Keuzes",
        "yourChoicesText1": "We respecteren uw privacy. U kunt de informatie die Google over u verzamelt, beheren en controleren door de pagina <a href=\"https://myactivity.google.com/myactivity\" target=\"_blank\">Mijn Activiteit</a> van Google te bezoeken. Daar kunt u uw activiteitsgegevens bekijken en verwijderen en uw instellingen voor advertentiepersonalisatie aanpassen.",
        "yourConsentHeader": "Uw Toestemming",
        "yourConsentText1": "Door onze website te gebruiken, stemt u in met onze gegevensverzameling en ons privacybeleid zoals hier beschreven.",
        "privacyButton": "Privacybeleid",
        "learnMore": "Meer informatie",
        "cookieAccept": "Begrepen!",
        "requestImageBtn": "Verzoek om een afbeelding toe te voegen",
        "requestImagePopupHeader": "Vraag een nieuwe afbeelding aan",
        "requestImagePopupNameLabel": "Naam:",
        "requestImagePopupLinkLabel": "Afbeeldingslink:",
        "requestImagePopupTypeLabel": "Type:",
        "requestImagePopupTypeLinkedin": "LinkedIn",
        "requestImagePopupTypeInterpol": "Interpol",
        "requestImagePopupSubmit": "Verzoek indienen",
        "instructionsBtn": "Instructies",
        "instructionsPopupHeader": "Hoe te Spelen",
        "instructionsPopupText1": "U krijgt een reeks afbeeldingen te zien.",
        "instructionsPopupText2": "Voor elke afbeelding moet u raden of de persoon een professional van LinkedIn is of een crimineel van Interpol.",
        "instructionsPopupText3": "Klik op de knop \"LinkedIn\" of \"Interpol\" om uw gok te maken.",
        "instructionsPopupText4": "Uw score wordt bovenaan de pagina bijgehouden.",
        "playButton": "Spelen"
    },
    "ru": {
        "title": "LinkedIn или Интерпол",
        "subtitle": "Профессионал или преступник? Решайте!",
        "score": "Счет",
        "total": "Всего",
        "autoAdvance": "Автоматический переход",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Интерпол",
        "nextButton": "Следующее изображение",
        "footerTitle": "LinkedIn или Интерпол - Детективная игра - Версия 1.0",
        "footerDisclaimer": "Отказ от ответственности: Этот сайт является сатирической и образовательной игрой-угадайкой.",
        "privacyPolicy": "Политика конфиденциальности",
        "termsOfService": "Условия использования",
        "copyright": "© 2025 Jan Queralt. Все права защищены.",
        "correct": "Правильно!",
        "wrong": "Неправильно!",
        "policeRecord": "Полицейское досье",
        "imgDesc1": "Этот человек на LinkedIn.",
        "imgDesc2": "Иранец, обвиненный ФБР во взломе.",
        "imgDesc3": "Этот человек на LinkedIn.",
        "imgDesc4": "Дело о незаконном обороте и распространении наркотиков ФБР.",
        "imgDesc5": "Этот человек на LinkedIn.",
        "imgDesc6": "Обвинения в заговоре и деятельности в качестве иностранного агента.",
        "imgDesc7": "Этот человек на LinkedIn.",
        "imgDesc8": "Кульков обвинен в киберпреступности.",
        "imgDesc9": "Этот человек на LinkedIn.",
        "imgDesc10": "Радованович обвинен в сговоре с целью своттинга.",
        "imgDesc11": "Этот человек на LinkedIn.",
        "imgDesc12": "Соколов обвинен в мошенничестве с кредитными картами.",
        "imgDesc13": "Этот человек на LinkedIn.",
        "imgDesc14": "Заговор с целью незаконного оборота фентанила и оружия.",
        "imgDesc15": "Этот человек на LinkedIn.",
        "imgDesc16": "Обвинения в сговоре с целью распространения наркотиков.",
        "imgDesc17": "Этот человек на LinkedIn.",
        "imgDesc18": "является частью преступной организации PSOE",
        "imgDesc19": "Этот человек на LinkedIn.",
        "imgDesc20": "Похищение ребенка Смрекаром.",
        "imgDesc21": "Этот человек на LinkedIn.",
        "imgDesc22": "Выданы международные ордера на арест за сговор с целью убийства.",
        "imgDesc23": "Этот человек на LinkedIn.",
        "imgDesc24": "Стеффен ван Хоа ДО разыскивается за ограбление с кокаином.",
        "imgDesc25": "Этот человек на LinkedIn.",
        "imgDesc26": "разыскивается за коррупцию на Тайване.",
        "imgDesc27": "Этот человек на LinkedIn.",
        "imgDesc28": "Обвинения в терроризме и киберпреступности.",
        "imgDesc29": "Этот человек на LinkedIn.",
        "imgDesc30": "разыскивается за убийство и покушение на убийство.",
        "imgDesc31": "Этот человек на LinkedIn.",
        "imgDesc32": "Лестер Юбэнкс разыскивается за убийство и побег.",
        "imgDesc33": "Этот человек на LinkedIn.",
        "imgDesc35": "Этот человек на LinkedIn.",
        "imgDesc37": "Этот человек на LinkedIn.",
        "imgDesc39": "Этот человек на LinkedIn.",
        "imgDesc41": "Этот человек на LinkedIn.",
        "imgDesc43": "Этот человек на LinkedIn.",
        "imgDesc45": "Этот человек на LinkedIn.",
        "imgDesc47": "Этот человек на LinkedIn.",
        "imgDesc49": "Этот человек на LinkedIn.",
        "professionalOrCriminal": "Профессионал или преступник?",
        "youDecide": "Решайте!",
        "aDeductionGame": "Детективная игра",
        "version": "Версия 1.0",
        "disclaimer": "Отказ от ответственности: Этот сайт является сатирической и образовательной игрой-угадайкой.",
        "allRightsReserved": "Все права защищены.",
        "metaDescription": "Забавная игра, в которой вам предстоит угадать, является ли человек профессионалом из LinkedIn или преступником из Интерпола.",
        "ogTitle": "LinkedIn или Интерпол",
        "ogDescription": "Забавная игра, в которой вам предстоит угадать, является ли человек профессионалом из LinkedIn или преступником из Интерпола.",
        "aboutTitle": "О - LinkedIn или Интерпол",
        "aboutHeader": "Об игре",
        "aboutText": "Эта игра была создана в развлекательных и образовательных целях, чтобы подчеркнуть сходства и различия в профессиональных и криминальных профилях. Все изображения используются в сатирических целях.",
        "disclaimerTitle": "Отказ от ответственности - LinkedIn или Интерпол",
        "disclaimerHeader": "Отказ от ответственности",
        "disclaimerText": "Этот сайт является сатирической и образовательной игрой-угадайкой. Он не связан с LinkedIn или Интерполом. Весь контент предназначен исключительно для развлекательных целей.",
        "backButton": "Назад к игре",
        "aboutButton": "О",
        "disclaimerButton": "Отказ от ответственности",
        "metaKeywords": "linkedin, интерпол, игра, профессионал, преступник, угадать",
        "privacyTitle": "Политика конфиденциальности - LinkedIn или Интерпол",
        "privacyHeaderV2": "Политика конфиденциальности",
        "privacyIntro": "Добро пожаловать на наш сайт. Мы хотим, чтобы вы понимали, какую информацию мы собираем и как ее используем. Чтобы улучшить эту игру и сохранить ее бесплатной, мы используем такие сервисы, как Google Analytics.",
        "whatDataHeader": "Какую информацию мы собираем?",
        "whatDataText1": "Когда вы используете наш сайт, мы автоматически собираем некоторую информацию, чтобы лучше понять нашу аудиторию. Это включает:",
        "whatDataPoint1": "<b>Общая информация о местоположении и устройстве:</b> Мы собираем данные, такие как ваш город и тип используемого вами устройства. Это помогает нам узнать, откуда наши пользователи и как они получают доступ к сайту.",
        "whatDataPoint2": "<b>Данные об использовании:</b> Мы видим, как вы взаимодействуете с игрой, что помогает нам улучшить пользовательский опыт.",
        "whatDataPoint3": "<b>Информация об учетной записи Google:</b> Если вы вошли в учетную запись Google и включили персонализацию рекламы, Google может делиться с нами анонимной демографической информацией, такой как ваш возрастной диапазон или интересы. Мы не получаем никакой вашей личной информации, такой как ваше имя или адрес электронной почты.",
        "howDataHeader": "Как мы используем эту информацию?",
        "howDataText1": "Собираемые нами данные помогают нам:",
        "howDataPoint1": "Улучшать и оптимизировать наш сайт и игру.",
        "howDataPoint2": "Показывать вам более релевантную рекламу.",
        "yourChoicesHeader": "Ваши данные и ваш выбор",
        "yourChoicesText1": "Мы уважаем вашу конфиденциальность. Вы можете контролировать и управлять информацией, которую Google собирает о вас, посетив страницу <a href=\"https://myactivity.google.com/myactivity\" target=\"_blank\">Моя активность</a> Google. Там вы можете просматривать и удалять свои данные об активности и настраивать параметры персонализации рекламы.",
        "yourConsentHeader": "Ваше согласие",
        "yourConsentText1": "Используя наш веб-сайт, вы соглашаетесь на сбор данных и нашу политику конфиденциальности, как описано здесь.",
        "privacyButton": "Политика конфиденциальности",
        "learnMore": "Узнать больше",
        "cookieAccept": "Понятно!",
        "requestImageBtn": "Запросить добавление изображения",
        "requestImagePopupHeader": "Запросить новое изображение",
        "requestImagePopupNameLabel": "Имя:",
        "requestImagePopupLinkLabel": "Ссылка на изображение:",
        "requestImagePopupTypeLabel": "Тип:",
        "requestImagePopupTypeLinkedin": "LinkedIn",
        "requestImagePopupTypeInterpol": "Интерпол",
        "requestImagePopupSubmit": "Отправить запрос",
        "instructionsBtn": "Инструкции",
        "instructionsPopupHeader": "Как играть",
        "instructionsPopupText1": "Вам будет показана серия изображений.",
        "instructionsPopupText2": "Для каждого изображения вы должны угадать, является ли человек профессионалом из LinkedIn или преступником из Интерпола.",
        "instructionsPopupText3": "Нажмите кнопку \"LinkedIn\" или \"Интерпол\", чтобы сделать свой выбор.",
        "instructionsPopupText4": "Ваш счет отслеживается в верхней части страницы.",
        "playButton": "Играть"
    }
};

const images = [
    // 50 imágenes reales con URLs corregidas
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc1' },
    { src: 'images/interpol_2.webp', type: 'interpol', name: 'Mohammed Reza Sabahi', recordUrl: 'https://www.fbi.gov/wanted/cyber/mohammed-reza-sabahi', descriptionKey: 'imgDesc2' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc3' },
    { src: 'images/interpol_4.jpg', type: 'interpol', name: 'John Joe Soto', recordUrl: 'https://www.fbi.gov/wanted/cei/john-joe-soto', descriptionKey: 'imgDesc4' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc5' },
    { src: 'images/interpol_6.jpg', type: 'interpol', name: 'Natalia Burlinova', recordUrl: 'https://www.fbi.gov/wanted/counterintelligence/natalia-burlinova', descriptionKey: 'imgDesc6' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc7' },
    { src: 'images/interpol_8.webp', type: 'interpol', name: 'Kulkov', recordUrl: 'https://www.secretservice.gov/investigations/mostwanted/kulkov', descriptionKey: 'imgDesc8' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc9' },
    { src: 'images/interpol_10.webp', type: 'interpol', name: 'Nemanja Radovanovic', recordUrl: 'https://www.secretservice.gov/investigations/mostwanted/radovanovic', descriptionKey: 'imgDesc10' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc11' },
    { src: 'images/interpol_12.webp', type: 'interpol', name: 'Sokolov', recordUrl: 'https://www.secretservice.gov/investigations/mostwanted/sokolov', descriptionKey: 'imgDesc12' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc13' },
    { src: 'images/interpol_14.jpg', type: 'interpol', name: 'Alan Gabriel Nunez-Herrera', recordUrl: 'https://www.dea.gov/fugitives/alan-gabriel-nunez-herrera', descriptionKey: 'imgDesc14' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc15' },
    { src: 'images/interpol_16.jpg', type: 'interpol', name: 'Hernandez De La Cruz', recordUrl: 'https://www.dea.gov/fugitives/benjamin-hernandez-de-la-cruz', descriptionKey: 'imgDesc16' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc17' },
    { src: 'images/interpol_18.jpg', type: 'interpol', name: 'Pedro Sanchez', recordUrl: 'https://es.wikipedia.org/wiki/Pedro_Sánchez', descriptionKey: 'imgDesc18' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc19' },
    { src: 'images/interpol_20.jpg', type: 'interpol', name: 'Melisa Smrekar', recordUrl: 'https://eumostwanted.eu/#/index.php/smrekar-melisa', descriptionKey: 'imgDesc20' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc21' },
    { src: 'images/interpol_22.png', type: 'interpol', name: 'Eva', recordUrl: 'https://eumostwanted.eu/#/zamecnikova-eva', descriptionKey: 'imgDesc22' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc23' },
    { src: 'images/interpol_24.jpg', type: 'interpol', name: 'Steffen van Khoa DO', recordUrl: 'https://eumostwanted.eu/#/do-steffen-van-khoa', descriptionKey: 'imgDesc24' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc25' },
    { src: 'images/interpol_26.jpg', type: 'interpol', name: 'Unknown', recordUrl: 'https://www.cib.npa.gov.tw/en/', descriptionKey: 'imgDesc26' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc27' },
    { src: 'images/interpol_28.png', type: 'interpol', name: 'Unknown', recordUrl: 'https://eumostwanted.eu/', descriptionKey: 'imgDesc28' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc29' },
    { src: 'images/interpol_30.jpg', type: 'interpol', name: 'Robert Lee King', recordUrl: 'https://www.usmarshals.gov/what-we-do/fugitive-apprehension/15-most-wanted-fugitive/robert-lee-king', descriptionKey: 'imgDesc30' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc31' },
    { src: 'images/interpol_32.jpg', type: 'interpol', name: 'Lester Edward Eubanks', recordUrl: 'https://www.usmarshals.gov/what-we-do/fugitive-apprehension/15-most-wanted-fugitive/lester-eubanks', descriptionKey: 'imgDesc32' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc33' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc35' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc37' },
    { src: 'https://thispersondoesnotexist.com/', type: "linkedin", descriptionKey: 'imgDesc39' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc41' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc43' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc45' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc47' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc49' },
];

let score = 0;
let total = 0;
let currentImage;
let remainingImages = [...images];
let autoAdvance = true;
let currentTranslations = {};

const profilePicture = document.getElementById('profile-picture');
const scoreSpan = document.getElementById('score');
const totalSpan = document.getElementById('total');
const linkedinButton = document.getElementById('linkedin-button');
const interpolButton = document.getElementById('interpol-button');
const feedbackEl = document.getElementById('feedback');
const descriptionEl = document.getElementById('description');
const nextButton = document.getElementById('next-button');
const autoAdvanceSwitch = document.getElementById('auto-advance-switch');
const languageSelector = document.getElementById('language-selector');
const instructionsLanguageSelector = document.getElementById('instructions-language-selector');

function loadLanguage(lang) {
    languageSelector.value = lang;
    instructionsLanguageSelector.value = lang;
    document.documentElement.lang = lang;
    currentTranslations = translations[lang];
    translatePage();
    updateMetaTags();
    updateStructuredData();
}

function updateStructuredData() {
    const structuredData = {
        "@context": "https://schema.org",
        "@type": "VideoGame",
        "name": currentTranslations.title,
        "description": currentTranslations.structuredDataDescription,
        "gamePlatform": "Web",
        "inLanguage": document.documentElement.lang,
        "applicationCategory": "Game",
        "operatingSystem": "Any",
        "genre": currentTranslations.structuredDataType,
        "author": {
            "@type": "Person",
            "name": "Jan Queralt"
        },
        "publisher": {
            "@type": "Person",
            "name": "Jan Queralt"
        },
        "keywords": currentTranslations.metaKeywords
    };
    document.getElementById('structured-data').textContent = JSON.stringify(structuredData);
}

function translatePage() {
    document.querySelectorAll('[data-i18n-key]').forEach(el => {
        const key = el.getAttribute('data-i18n-key');
        if (currentTranslations[key]) {
            el.textContent = currentTranslations[key];
        }
    });
}

function updateMetaTags() {
    document.querySelector('meta[name="description"]').setAttribute('content', currentTranslations.metaDescription);
    document.querySelector('meta[property="og:title"]').setAttribute('content', currentTranslations.ogTitle);
    document.querySelector('meta[property="og:description"]').setAttribute('content', currentTranslations.ogDescription);
    document.querySelector('meta[name="keywords"]').setAttribute('content', currentTranslations.metaKeywords);
}

function nextImage() {
    feedbackEl.textContent = '';
    feedbackEl.className = '';
    descriptionEl.textContent = '';
    nextButton.classList.add('hidden');
    linkedinButton.disabled = false;
    interpolButton.disabled = false;

    if (remainingImages.length === 0) {
        // Reshuffle the images to play again
        remainingImages = [...images];
    }

    const randomIndex = Math.floor(Math.random() * remainingImages.length);
    currentImage = remainingImages.splice(randomIndex, 1)[0];
    profilePicture.src = currentImage.src;
    total++;
    totalSpan.textContent = total;
}

function checkAnswer(guess) {
    if (guess === currentImage.type) {
        score++;
        scoreSpan.textContent = score;
        feedbackEl.textContent = currentTranslations.correct;
        feedbackEl.className = 'correct';
    } else {
        feedbackEl.textContent = currentTranslations.wrong;
        feedbackEl.className = 'incorrect';
    }

    descriptionEl.textContent = currentTranslations[currentImage.descriptionKey];

    if (currentImage.type === 'interpol') {
        const name = currentImage.name;
        const recordUrl = currentImage.recordUrl;
        const policeRecordLink = document.createElement('a');
        policeRecordLink.href = recordUrl;
        policeRecordLink.textContent = currentTranslations.policeRecord;
        policeRecordLink.target = '_blank';
        descriptionEl.innerHTML = `<b>${name}</b> - ${currentTranslations[currentImage.descriptionKey]} <br> `;
        descriptionEl.appendChild(policeRecordLink);
    } else {
        descriptionEl.textContent = currentTranslations[currentImage.descriptionKey];
    }

    linkedinButton.disabled = true;
    interpolButton.disabled = true;

    if (autoAdvance) {
        setTimeout(nextImage, 3000);
    } else {
        nextButton.classList.remove('hidden');
    }
}

function handleAutoAdvanceChange() {
    autoAdvance = autoAdvanceSwitch.checked;
}

function handleLanguageChange() {
    loadLanguage(languageSelector.value);
}

function handleInstructionsLanguageChange() {
    loadLanguage(instructionsLanguageSelector.value);
}

linkedinButton.addEventListener('click', () => checkAnswer('linkedin'));
interpolButton.addEventListener('click', () => checkAnswer('interpol'));
nextButton.addEventListener('click', nextImage);
autoAdvanceSwitch.addEventListener('change', handleAutoAdvanceChange);
languageSelector.addEventListener('change', handleLanguageChange);
instructionsLanguageSelector.addEventListener('change', handleInstructionsLanguageChange);

document.addEventListener('DOMContentLoaded', () => {
    // Initial load
    const userLang = navigator.language || navigator.userLanguage;
    const langCode = userLang.split('-')[0];

    if (translations[langCode]) {
        loadLanguage(langCode);
    } else {
        loadLanguage('en');
    }
    nextImage();
    const banner = document.getElementById('cookie-banner');
    const acceptButton = document.getElementById('cookie-accept');

    if (banner && acceptButton) {
        if (localStorage.getItem('cookieConsent') === 'true') {
            banner.style.display = 'none';
        } else {
            banner.style.display = 'flex';
        }

        acceptButton.addEventListener('click', () => {
            localStorage.setItem('cookieConsent', 'true');
            banner.style.display = 'none';
        });
    }

    const requestBtn = document.getElementById('request-image-btn');
    const popup = document.getElementById('request-image-popup');
    const closeBtn = document.querySelector('.close-btn');

    if (requestBtn && popup && closeBtn) {
        requestBtn.addEventListener('click', () => {
            popup.style.display = 'block';
        });

        closeBtn.addEventListener('click', () => {
            popup.style.display = 'none';
        });

        window.addEventListener('click', (event) => {
            if (event.target === popup) {
                popup.style.display = 'none';
            }
        });
    }

    const instructionsBtn = document.getElementById('instructions-btn');
    const instructionsPopup = document.getElementById('instructions-popup');
    const closeInstructionsBtn = document.querySelector('.close-instructions-btn');
    const playButton = document.getElementById('play-button');

    if (instructionsBtn && instructionsPopup && closeInstructionsBtn && playButton) {
        instructionsPopup.style.display = 'block';

        instructionsBtn.addEventListener('click', () => {
            instructionsPopup.style.display = 'block';
        });

        closeInstructionsBtn.addEventListener('click', () => {
            instructionsPopup.style.display = 'none';
        });

        playButton.addEventListener('click', () => {
            instructionsPopup.style.display = 'none';
        });

        window.addEventListener('click', (event) => {
            if (event.target === instructionsPopup) {
                instructionsPopup.style.display = 'none';
            }
        });
    }
});
