const translations = {
    "en": {
        "title": "LinkedIn or Interpol",
        "subtitle": "Professional or Criminal? You decide!",
        "score": "Score",
        "total": "Total",
        "autoAdvance": "Auto-Advance",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Next Image",
        "footerTitle": "LinkedIn or Interpol - A Deduction Game - Version 1.0",
        "footerDisclaimer": "Disclaimer: This website is a satirical and educational guessing game.",
        "privacyPolicy": "Privacy Policy",
        "termsOfService": "Terms of Service",
        "copyright": "© 2025 Jan Queralt. All rights reserved.",
        "correct": "Correct!",
        "wrong": "Wrong!",
        "policeRecord": "Police Record",
        "imgDesc1": "This person is on LinkedIn.",
        "imgDesc2": "Iranian indicted for hacking by FBI.",
        "imgDesc3": "This person is on LinkedIn.",
        "imgDesc4": "Drug trafficking and distribution case by FBI.",
        "imgDesc5": "This person is on LinkedIn.",
        "imgDesc6": "Conspiracy and foreign agent charges.",
        "imgDesc7": "This person is on LinkedIn.",
        "imgDesc8": "Kulkov indicted for cybercrime.",
        "imgDesc9": "This person is on LinkedIn.",
        "imgDesc10": "Radovanovic charged with swatting conspiracy.",
        "imgDesc11": "This person is on LinkedIn.",
        "imgDesc12": "Sokolov indicted for credit card fraud.",
        "imgDesc13": "This person is on LinkedIn.",
        "imgDesc14": "Fentanyl and weapons trafficking conspiracy.",
        "imgDesc15": "This person is on LinkedIn.",
        "imgDesc16": "Drug distribution conspiracy charges.",
        "imgDesc17": "This person is on LinkedIn.",
        "imgDesc18": "is part of the PSOE criminal organization",
        "imgDesc19": "This person is on LinkedIn.",
        "imgDesc20": "Child abduction by Smrekar.",
        "imgDesc21": "This person is on LinkedIn.",
        "imgDesc22": "International arrest warrants issued for assassination plot.",
        "imgDesc23": "This person is on LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO wanted for cocaine robbery.",
        "imgDesc25": "This person is on LinkedIn.",
        "imgDesc26": "wanted for corruption in Taiwan.",
        "imgDesc27": "This person is on LinkedIn.",
        "imgDesc28": "Terrorism and cybercrime charges.",
        "imgDesc29": "This person is on LinkedIn.",
        "imgDesc30": " wanted for murder and attempted murder.",
        "imgDesc31": "This person is on LinkedIn.",
        "imgDesc32": "Lester Eubanks wanted for murder and escape.",
        "imgDesc33": "This person is on LinkedIn.",
        "imgDesc35": "This person is on LinkedIn.",
        "imgDesc37": "This person is on LinkedIn.",
        "imgDesc39": "This person is on LinkedIn.",
        "imgDesc41": "This person is on LinkedIn.",
        "imgDesc43": "This person is on LinkedIn.",
        "imgDesc45": "This person is on LinkedIn.",
        "imgDesc47": "This person is on LinkedIn.",
        "imgDesc49": "This person is on LinkedIn.",
        "professionalOrCriminal": "Professional or Criminal?",
        "youDecide": "You decide!",
        "aDeductionGame": "A Deduction Game",
        "version": "Version 1.0",
        "disclaimer": "Disclaimer: This website is a satirical and educational guessing game.",
        "allRightsReserved": "All rights reserved.",
        "metaDescription": "A fun game where you have to guess if a person is a LinkedIn professional or an Interpol criminal.",
        "ogTitle": "LinkedIn or Interpol",
        "ogDescription": "A fun game where you have to guess if a person is a LinkedIn professional or an Interpol criminal.",
        "aboutTitle": "About - LinkedIn or Interpol",
        "aboutHeader": "About the Game",
        "aboutText": "This game was created for entertainment and educational purposes to highlight the similarities and differences in professional and criminal profiles. All images are used for satirical purposes.",
        "disclaimerTitle": "Disclaimer - LinkedIn or Interpol",
        "disclaimerHeader": "Disclaimer",
        "disclaimerText": "This website is a satirical and educational guessing game. It is not affiliated with LinkedIn or Interpol. All content is for entertainment purposes only.",
        "backButton": "Back to the game",
        "aboutButton": "About",
        "disclaimerButton": "Disclaimer",
        "metaKeywords": "linkedin, interpol, game, professional, criminal, guess",
        "privacyTitle": "Privacy Policy - LinkedIn or Interpol",
        "privacyHeader": "Data Collection Policy",
        "googleSignalsHeader": "Google Signals Data Collection",
        "googleSignalsText1": "If you activate Google Signals, you will allow Google Analytics to collect data about your traffic, in addition to the data it already collects through the standard implementation of Google Analytics, to offer you more features. Google Signals will not be included in the identity for Google Analytics reports.",
        "googleSignalsText2": "When Google Signals is activated, Google Analytics will collect visit information and associate it with information that Google already has from the accounts of users who have logged in and authorized this association to see personalized ads. Google's information may include the location of end-users, search history, YouTube history, and data from sites that are associated with Google. By activating Google Signals, you agree to comply with Google's Advertising Features policy, including the rules on sensitive categories; you also confirm that end-users have granted you the relevant private information disclosure rights and permissions to make this association, and that such users can access and delete that data through the My Activity page.",
        "googleSignalsText3": "Google Signals data collection is allowed in 307 of 307 territories.",
        "googleSignalsText4": "Note: If you use the switch above to enable this feature, Google Analytics will automatically collect additional information about your traffic to provide additional user statistics and enable the option to share audiences. If you do not want to collect Google Signals data, disable this feature with the switch and check that you have not manually enabled Remarketing and Advertising Reporting Features in your Google Analytics tags.",
        "userIdHeader": "User-ID and User-Provided Data Collection",
        "userIdText1": "User-provided data collection policy accepted",
        "userIdText2": "Improve measurement and enable additional features with your Google Ads integrations. With User-ID and user-provided data, you can use your own data to know how users interact with your website and your applications, improve conversion measurement, and complement audience sharing features if you link your Analytics property with Google Ads accounts. More information about User-ID.",
        "userIdText3": "User-ID Collection",
        "userIdText4": "Receiving data in 0 of 1 data streams.",
        "userIdText5": "The User-ID feature allows you to provide your own identifiers to users of your site and application so that you can relate their behavior in different sessions, as well as on the different devices and platforms from which they visit you. Google Analytics interprets each user ID as an independent user, which provides you with more accurate user counts and a more complete view of each user's interactions with your company. More information about User-ID.",
        "userIdText6": "You are responsible for using the User-ID feature in accordance with the Google Analytics Terms of Service. This includes not sending personally identifiable information to Google Analytics as a User-ID and adequately notifying the use of identifiers in your privacy policy. See how to send user IDs to Google Analytics in Send user IDs.",
        "userIdText7": "Collection of user-provided data (Beta)",
        "userIdText8": "Receiving data in 0 of 1 data streams.",
        "userIdText9": "The policy for the user-provided data collection feature was accepted on Nov 11, 2025. See the policy.",
        "userIdText10": "This will improve user and conversion measurement by providing you with more detailed audience data. To use features such as improved conversion measurement and audience sharing, you must have linked advertising accounts and ad personalization activated in your Google Analytics property. The collection of user-provided data complements the data you already have from Google Analytics, as it allows you to send consented and hash-encrypted customer data to Google Analytics without violating their privacy. More information about the collection of user-provided data.",
        "userIdText11": "By activating the collection of user-provided data, you confirm that you comply with the policy of the user-provided data feature and the requirement to have the necessary privacy notices and rights of end-users for such use. In accordance with our policy, the use of this feature is prohibited for customers in sensitive categories.",
        "userIdText12": "Collect automatically detected user-provided data.",
        "granularDataHeader": "Granular Location and Device Data Collection",
        "granularDataText1": "When you activate the collection of granular location and device data, Analytics collects metadata about the city-level location and granular details about the devices of your site visitors and app users to offer location and device-based features.",
        "granularDataText2": "The collection of granular location and device data is allowed in 307 of 307 territories.",
        "granularDataText3": "Territory and country-level metadata is collected by default in relation to all your traffic to comply with territorial privacy policies and for territory-based Analytics settings to work. For more information about location and device data collection settings, see the article Collect granular location and device data.",
        "adPersonalizationHeader": "Advanced Settings to Allow Ad Personalization",
        "adPersonalizationText1": "When ad personalization is enabled, you can export your Google Analytics audiences and key events to your linked Google Ads accounts to offer relevant and personalized experiences to your end-users.",
        "adPersonalizationText2": "Ads can be personalized in 307 of 307 regions.",
        "adPersonalizationText3": "You can configure Google Analytics at the property level to collect data for ad personalization and measurement purposes, in relation to the use of features such as Google Signals, User-ID, and ad integrations, or if you enable the option to share data with Google. If you disable ad personalization, shared remarketing lists will be marked as inactive and new users will not be shared through remarketing lists. In addition, the exported data (whether audiences exported through an integration or data shared through the Google products and services sharing option) will not be used to personalize ads. More information.",
        "adPersonalizationText4": "For more information on how to disable the use of data that Analytics collects from your users through the SDK or the Google tag to personalize ads, see the following resources: Use Google Analytics for Firebase and Use the Google tag in Google Analytics.",
        "userConsentHeader": "User Data Collection Consent",
        "userConsentText1": "Confirmed",
        "userConsentText2": "I confirm that I have provided the necessary privacy notices and have obtained the consent of my end-users to collect and process their data (for example, to associate it with the visit information that Google Analytics collects from my website or app property).",
        "userConsentText3": "Confirmed",
        "privacyButton": "Privacy Policy",
        "learnMore": "Learn more",
        "cookieAccept": "Got it!"
    },
    "es": {
        "title": "LinkedIn o Interpol",
        "subtitle": "¿Profesional o Criminal? ¡Tú decides!",
        "score": "Puntuación",
        "total": "Total",
        "autoAdvance": "Avance Automático",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Siguiente Imagen",
        "footerTitle": "LinkedIn o Interpol - Un Juego de Deducción - Versión 1.0",
        "footerDisclaimer": "Aviso: Este sitio web es un juego de adivinanzas satírico y educativo.",
        "privacyPolicy": "Política de Privacidad",
        "termsOfService": "Términos de Servicio",
        "copyright": "© 2025 Jan Queralt. Todos los derechos reservados.",
        "correct": "¡Correcto!",
        "wrong": "¡Incorrecto!",
        "policeRecord": "Antecedentes Policiales",
        "imgDesc1": "Esta persona está en LinkedIn.",
        "imgDesc2": "Iraní acusado de piratería por el FBI.",
        "imgDesc3": "Esta persona está en LinkedIn.",
        "imgDesc4": "Caso de narcotráfico y distribución por el FBI.",
        "imgDesc5": "Esta persona está en LinkedIn.",
        "imgDesc6": "Cargos de conspiración y agente extranjero.",
        "imgDesc7": "Esta persona está en LinkedIn.",
        "imgDesc8": "Kulkov acusado de ciberdelincuencia.",
        "imgDesc9": "Esta persona está en LinkedIn.",
        "imgDesc10": "Radovanovic acusado de conspiración de swatting.",
        "imgDesc11": "Esta persona está en LinkedIn.",
        "imgDesc12": "Sokolov acusado de fraude con tarjetas de crédito.",
        "imgDesc13": "Esta persona está en LinkedIn.",
        "imgDesc14": "Conspiración de tráfico de fentanilo y armas.",
        "imgDesc15": "Esta persona está en LinkedIn.",
        "imgDesc16": "Cargos de conspiración para distribuir drogas.",
        "imgDesc17": "Esta persona está en LinkedIn.",
        "imgDesc18": "forma parte de la organización criminal PSOE",
        "imgDesc19": "Esta persona está en LinkedIn.",
        "imgDesc20": "Secuestro de menores por Smrekar.",
        "imgDesc21": "Esta persona está en LinkedIn.",
        "imgDesc22": "Órdenes de arresto internacionales emitidas por complot de asesinato.",
        "imgDesc23": "Esta persona está en LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO buscado por robo de cocaína.",
        "imgDesc25": "Esta persona está en LinkedIn.",
        "imgDesc26": "buscado por corrupción en Taiwán.",
        "imgDesc27": "Esta persona está en LinkedIn.",
        "imgDesc28": "Cargos de terrorismo y ciberdelincuencia.",
        "imgDesc29": "Esta persona está en LinkedIn.",
        "imgDesc30": "buscado por asesinato y tentativa de asesinato.",
        "imgDesc31": "Esta persona está en LinkedIn.",
        "imgDesc32": "Lester Eubanks buscado por asesinato y fuga.",
        "imgDesc33": "Esta persona está en LinkedIn.",
        "imgDesc35": "Esta persona está en LinkedIn.",
        "imgDesc37": "Esta persona está en LinkedIn.",
        "imgDesc39": "Esta persona está en LinkedIn.",
        "imgDesc41": "Esta persona está en LinkedIn.",
        "imgDesc43": "Esta persona está en LinkedIn.",
        "imgDesc45": "Esta personá está en LinkedIn.",
        "imgDesc47": "Esta persona está en LinkedIn.",
        "imgDesc49": "Esta persona está en LinkedIn.",
        "professionalOrCriminal": "¿Profesional o Criminal?",
        "youDecide": "¡Tú decides!",
        "aDeductionGame": "Un Juego de Deducción",
        "version": "Versión 1.0",
        "disclaimer": "Aviso: Este sitio web es un juego de adivinanzas satírico y educativo.",
        "allRightsReserved": "Todos los derechos reservados.",
        "metaDescription": "Un divertido juego donde tienes que adivinar si una persona es un profesional de LinkedIn o un criminal de Interpol.",
        "ogTitle": "LinkedIn o Interpol",
        "ogDescription": "Un divertido juego donde tienes que adivinar si una persona es un profesional de LinkedIn o un criminal de Interpol.",
        "aboutTitle": "Acerca de - LinkedIn o Interpol",
        "aboutHeader": "Acerca del Juego",
        "aboutText": "Este juego fue creado con fines de entretenimiento y educativos para resaltar las similitudes y diferencias en los perfiles profesionales y criminales. Todas las imágenes se utilizan con fines satíricos.",
        "disclaimerTitle": "Aviso Legal - LinkedIn o Interpol",
        "disclaimerHeader": "Aviso Legal",
        "disclaimerText": "Este sitio web es un juego de adivinanzas satírico y educativo. No está afiliado a LinkedIn ni a Interpol. Todo el contenido es solo para fines de entretenimiento.",
        "backButton": "Volver al juego",
        "aboutButton": "Acerca de",
        "disclaimerButton": "Aviso Legal",
        "metaKeywords": "linkedin, interpol, juego, profesional, criminal, adivinar",
        "privacyTitle": "Política de Privacidad - LinkedIn o Interpol",
        "privacyHeader": "Política de Recogida de Datos",
        "googleSignalsHeader": "Recogida de Datos de Google Signals",
        "googleSignalsText1": "Si activa Google signals, permitirá que Google Analytics recoja datos sobre su tráfico, además de los datos que ya recoge mediante la implementación estándar de Google Analytics, para ofrecerle más funciones. Google signals no se incluirá en la identidad para los informes de Google Analytics.",
        "googleSignalsText2": "Cuando Google signals esté activado, Google Analytics recogerá información de visitas y la asociará a la información que Google ya tiene de las cuentas de usuarios que hayan iniciado sesión y hayan autorizado esta asociación para ver anuncios personalizados. La información de Google puede incluir la ubicación de los usuarios finales, el historial de búsqueda, el historial de YouTube y datos de sitios que están asociados con Google. Al activar Google signals, acepta cumplir la política de Funciones publicitarias de Google, incluidas las reglas sobre categorías sensibles; también confirma que los usuarios finales le han otorgado los derechos y permisos de divulgación de información privada pertinentes para hacer esta asociación, y que dichos usuarios pueden acceder a esos datos y eliminarlos a través de la página Mi Actividad.",
        "googleSignalsText3": "La recogida de datos de Google signals está permitida en 307 de 307 territorios.",
        "googleSignalsText4": "Nota: Si usas el interruptor de arriba para habilitar esta función, Google Analytics recogerá automáticamente información adicional sobre tu tráfico para proporcionar estadísticas adicionales sobre los usuarios y habilitar la opción de compartir audiencias. Si no quieres recoger datos de Google signals, inhabilita esta función con el interruptor y comprueba que no has habilitado manualmente Remarketing y Funciones de generación de informes publicitarios en tus etiquetas de Google Analytics.",
        "userIdHeader": "Recogida de datos de User-ID y de datos proporcionados por los usuarios",
        "userIdText1": "Política de recogida de datos proporcionados por los usuarios aceptada",
        "userIdText2": "Mejora la medición y habilita funciones adicionales con tus integraciones con Google Ads. Con los datos de User-ID y los datos proporcionados por los usuarios, puedes utilizar tus datos propios para saber cómo interactúan los usuarios con tu sitio web y tus aplicaciones, mejorar la medición de conversiones y complementar las funciones para compartir audiencias si vinculas tu propiedad de Analytics con cuentas de Google Ads. Más información sobre User-ID.",
        "userIdText3": "Recogida de User-ID",
        "userIdText4": "Recibiendo datos en 0 de 1 flujos de datos.",
        "userIdText5": "La función User-ID te permite proporcionar tus propios identificadores a los usuarios de tu sitio y tu aplicación para que puedas relacionar su comportamiento en diferentes sesiones, así como en los distintos dispositivos y plataformas desde los que te visitan. Google Analytics interpreta cada ID de usuario como un usuario independiente, lo que te proporciona recuentos de usuarios más precisos y una visión más completa de las interacciones de cada usuario con tu empresa. Más información sobre User-ID.",
        "userIdText6": "Tienes la responsabilidad de usar la función User-ID de acuerdo con los Términos del Servicio de Google Analytics. Esto incluye no enviar información de identificación personal a Google Analytics como User-ID y notificar adecuadamente el uso de identificadores en tu política de privacidad. Consulta cómo enviar IDs de usuario a Google Analytics en Enviar IDs de usuario.",
        "userIdText7": "Recogida de datos proporcionados por los usuarios (Beta)",
        "userIdText8": "Recibiendo datos en 0 de 1 flujos de datos.",
        "userIdText9": "La política de la función de recogida de datos proporcionados por los usuarios se aceptó el 11 nov 2025. Consulta la política.",
        "userIdText10": "De este modo, mejorará la medición de usuarios y conversiones, ya que te proporcionará datos de audiencia más detallados. Para usar funciones como la mejora de la medición de conversiones y el uso compartido de audiencias, debes tener cuentas publicitarias vinculadas y la personalización de anuncios activada en tu propiedad de Google Analytics. La recogida de datos proporcionados por los usuarios complementa los datos que ya tienes de Google Analytics, puesto que te permite enviar datos de clientes con consentimiento y cifrados con hash a Google Analytics sin vulnerar su privacidad. Más información sobre la recogida de datos proporcionados por los usuarios.",
        "userIdText11": "Al activar la recogida de datos proporcionados por los usuarios, confirma que cumples la política de la función de datos proporcionados por los usuarios y el requisito de tener los avisos y derechos de privacidad necesarios de los usuarios finales para dicho uso. De acuerdo con nuestra política, el uso de esta función está prohibido para los clientes de categorías sensibles.",
        "userIdText12": "Recoger datos proporcionados por los usuarios detectados automáticamente.",
        "granularDataHeader": "Recogida de datos granulares de ubicación y dispositivo",
        "granularDataText1": "Cuando activas la recogida de datos granulares de ubicación y dispositivo, Analytics recoge metadatos sobre la ubicación a nivel de ciudad y detalles granulares sobre los dispositivos de los visitantes de tu sitio y de los usuarios de tu app para ofrecer funciones basadas en la ubicación y el dispositivo.",
        "granularDataText2": "La recogida de datos granulares de ubicación y dispositivo está permitida en 307 de 307 territorios.",
        "granularDataText3": "Los metadatos a nivel de territorio y país se recogen de forma predeterminada en relación con todo tu tráfico para cumplir las políticas de privacidad territoriales y para que funcionen los ajustes de Analytics basados en el territorio. Para obtener más información sobre los ajustes de recogida de datos de ubicación y dispositivo, consulta el artículo Recoger datos granulares de ubicación y dispositivo.",
        "adPersonalizationHeader": "Configuración avanzada para permitir la personalización de anuncios",
        "adPersonalizationText1": "Cuando la personalización de anuncios esté habilitada, podrás exportar tus audiencias y eventos clave de Google Analytics a tus cuentas vinculadas de Google Ads para ofrecer experiencias relevantes y personalizadas a tus usuarios finales.",
        "adPersonalizationText2": "Se pueden personalizar anuncios en 307 de 307 regiones.",
        "adPersonalizationText3": "Puedes configurar Google Analytics a nivel de propiedad para recoger datos con fines de personalización de anuncios y de medición, en relación con el uso de funciones como Google signals, User-ID e integraciones de anuncios, o bien si habilitas la opción para compartir datos con Google. Si inhabilitas la personalización de anuncios, las listas de remarketing compartidas se marcarán como inactivas y no se compartirán nuevos usuarios a través de listas de remarketing. Además, los datos exportados (ya sean audiencias exportadas a través de una integración o datos compartidos mediante la opción para compartir de los productos y servicios de Google) no se usarán para personalizar anuncios. Más información.",
        "adPersonalizationText4": "Para obtener más información sobre cómo inhabilitar el uso de los datos que Analytics recoge de tus usuarios a través del SDK o la etiqueta de Google para personalizar anuncios, consulta los siguientes recursos: Usar Google Analytics for Firebase y Usar la etiqueta de Google en Google Analytics.",
        "userConsentHeader": "Consentimiento de recogida de datos de usuario",
        "userConsentText1": "Confirmado",
        "userConsentText2": "Confirmo que he dispuesto los avisos de privacidad necesarios y he obtenido el consentimiento de mis usuarios finales para recoger y tratar sus datos (por ejemplo, para asociarlos a la información de visitas que Google Analytics recoge de mi propiedad de sitio web o app).",
        "userConsentText3": "Confirmado",
        "privacyButton": "Política de Privacidad",
        "learnMore": "Leer más",
        "cookieAccept": "¡Entendido!"
    },
    "fr": {
        "title": "LinkedIn ou Interpol",
        "subtitle": "Professionnel ou Criminel? À vous de décider!",
        "score": "Score",
        "total": "Total",
        "autoAdvance": "Avance Automatique",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Image Suivante",
        "footerTitle": "LinkedIn ou Interpol - Un Jeu de Déduction - Version 1.0",
        "footerDisclaimer": "Avertissement: Ce site web est un jeu de devinettes satirique et éducatif.",
        "privacyPolicy": "Politique de Confidentialité",
        "termsOfService": "Conditions d'Utilisation",
        "copyright": "© 2025 Jan Queralt. Tous droits réservés.",
        "correct": "Correct!",
        "wrong": "Faux!",
        "policeRecord": "Dossier de Police",
        "imgDesc1": "Cette personne est sur LinkedIn.",
        "imgDesc2": "Iranien inculpé de piratage par le FBI.",
        "imgDesc3": "Cette personne est sur LinkedIn.",
        "imgDesc4": "Affaire de trafic et de distribution de drogue par le FBI.",
        "imgDesc5": "Cette personne est sur LinkedIn.",
        "imgDesc6": "Accusations de complot et d'agent étranger.",
        "imgDesc7": "Cette personne est sur LinkedIn.",
        "imgDesc8": "Kulkov inculpé de cybercriminalité.",
        "imgDesc9": "Cette personne est sur LinkedIn.",
        "imgDesc10": "Radovanovic accusé de complot de swatting.",
        "imgDesc11": "Cette personne est sur LinkedIn.",
        "imgDesc12": "Sokolov inculpé de fraude à la carte de crédit.",
        "imgDesc13": "Cette personne est sur LinkedIn.",
        "imgDesc14": "Complot de trafic de fentanyl et d'armes.",
        "imgDesc15": "Cette personne est sur LinkedIn.",
        "imgDesc16": "Accusations de complot pour distribution de drogue.",
        "imgDesc17": "Cette personne est sur LinkedIn.",
        "imgDesc18": "fait partie de l'organisation criminelle PSOE",
        "imgDesc19": "Cette personne est sur LinkedIn.",
        "imgDesc20": "Enlèvement d'enfant par Smrekar.",
        "imgDesc21": "Cette personne est sur LinkedIn.",
        "imgDesc22": "Mandats d'arrêt internationaux émis pour complot d'assassinat.",
        "imgDesc23": "Cette personne est sur LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO recherché pour vol de cocaïne.",
        "imgDesc25": "Cette personne est sur LinkedIn.",
        "imgDesc26": "recherché pour corruption à Taïwan.",
        "imgDesc27": "Cette personne est sur LinkedIn.",
        "imgDesc28": "Accusations de terrorisme et de cybercriminalité.",
        "imgDesc29": "Cette personne est sur LinkedIn.",
        "imgDesc30": "recherché pour meurtre et tentative de meurtre.",
        "imgDesc31": "Cette personne est sur LinkedIn.",
        "imgDesc32": "Lester Eubanks recherché pour meurtre et évasion.",
        "imgDesc33": "Cette personne est sur LinkedIn.",
        "imgDesc35": "Cette personne est sur LinkedIn.",
        "imgDesc37": "Cette personne est sur LinkedIn.",
        "imgDesc39": "Cette personne est sur LinkedIn.",
        "imgDesc41": "Cette personne est sur LinkedIn.",
        "imgDesc43": "Cette personne est sur LinkedIn.",
        "imgDesc45": "Cette personne est sur LinkedIn.",
        "imgDesc47": "Cette personne est sur LinkedIn.",
        "imgDesc49": "Cette personne est sur LinkedIn.",
        "professionalOrCriminal": "Professionnel ou Criminel?",
        "youDecide": "À vous de décider!",
        "aDeductionGame": "Un Jeu de Déduction",
        "version": "Version 1.0",
        "disclaimer": "Avertissement: Ce site web est un jeu de devinettes satirique et éducatif.",
        "allRightsReserved": "Tous droits réservés.",
        "metaDescription": "Un jeu amusant où vous devez deviner si une personne est un professionnel de LinkedIn ou un criminel d'Interpol.",
        "ogTitle": "LinkedIn ou Interpol",
        "ogDescription": "Un jeu amusant où vous devez deviner si une personne est un professionnel de LinkedIn ou un criminel d'Interpol.",
        "aboutTitle": "À propos - LinkedIn ou Interpol",
        "aboutHeader": "À propos du jeu",
        "aboutText": "Ce jeu a été créé à des fins de divertissement et d'éducation pour souligner les similitudes et les différences entre les profils professionnels et criminels. Toutes les images sont utilisées à des fins satiriques.",
        "disclaimerTitle": "Avis de non-responsabilité - LinkedIn ou Interpol",
        "disclaimerHeader": "Avis de non-responsabilité",
        "disclaimerText": "Ce site web est un jeu de devinettes satirique et éducatif. Il n'est affilié ni à LinkedIn ni à Interpol. Tout le contenu est uniquement à des fins de divertissement.",
        "backButton": "Retour au jeu",
        "aboutButton": "À propos",
        "disclaimerButton": "Avis",
        "metaKeywords": "linkedin, interpol, jeu, professionnel, criminel, deviner"
    },
    "de": {
        "title": "LinkedIn oder Interpol",
        "subtitle": "Profi oder Verbrecher? Du entscheidest!",
        "score": "Punktzahl",
        "total": "Gesamt",
        "autoAdvance": "Automatischer Vorlauf",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Nächstes Bild",
        "footerTitle": "LinkedIn oder Interpol - Ein Deduktionsspiel - Version 1.0",
        "footerDisclaimer": "Haftungsausschluss: Diese Website ist ein satirisches und lehrreiches Ratespiel.",
        "privacyPolicy": "Datenschutzrichtlinie",
        "termsOfService": "Nutzungsbedingungen",
        "copyright": "© 2025 Jan Queralt. Alle Rechte vorbehalten.",
        "correct": "Richtig!",
        "wrong": "Falsch!",
        "policeRecord": "Polizeiakte",
        "imgDesc1": "Diese Person ist auf LinkedIn.",
        "imgDesc2": "Iraner vom FBI des Hackens angeklagt.",
        "imgDesc3": "Diese Person ist auf LinkedIn.",
        "imgDesc4": "Fall von Drogenhandel und -verteilung durch das FBI.",
        "imgDesc5": "Diese Person ist auf LinkedIn.",
        "imgDesc6": "Anklage wegen Verschwörung und Agententätigkeit für eine ausländische Macht.",
        "imgDesc7": "Diese Person ist auf LinkedIn.",
        "imgDesc8": "Kulkov wegen Cyberkriminalität angeklagt.",
        "imgDesc9": "Diese Person ist auf LinkedIn.",
        "imgDesc10": "Radovanovic wegen Swatting-Verschwörung angeklagt.",
        "imgDesc11": "Diese Person ist auf LinkedIn.",
        "imgDesc12": "Sokolov wegen Kreditkartenbetrugs angeklagt.",
        "imgDesc13": "Diese Person ist auf LinkedIn.",
        "imgDesc14": "Verschwörung zum Handel mit Fentanyl und Waffen.",
        "imgDesc15": "Diese Person ist auf LinkedIn.",
        "imgDesc16": "Anklage wegen Verschwörung zum Drogenhandel.",
        "imgDesc17": "Diese Person ist auf LinkedIn.",
        "imgDesc18": "ist Teil der kriminellen Organisation PSOE",
        "imgDesc19": "Diese Person ist auf LinkedIn.",
        "imgDesc20": "Kindesentführung durch Smrekar.",
        "imgDesc21": "Diese Person ist auf LinkedIn.",
        "imgDesc22": "Internationale Haftbefehle wegen Mordkomplotts erlassen.",
        "imgDesc23": "Diese Person ist auf LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO wegen Kokainraubs gesucht.",
        "imgDesc25": "Diese Person ist auf LinkedIn.",
        "imgDesc26": "wegen Korruption in Taiwan gesucht.",
        "imgDesc27": "Diese Person ist auf LinkedIn.",
        "imgDesc28": "Anklage wegen Terrorismus und Cyberkriminalität.",
        "imgDesc29": "Diese Person ist auf LinkedIn.",
        "imgDesc30": "wegen Mordes und versuchten Mordes gesucht.",
        "imgDesc31": "Diese Person ist auf LinkedIn.",
        "imgDesc32": "Lester Eubanks wegen Mordes und Flucht gesucht.",
        "imgDesc33": "Diese Person ist auf LinkedIn.",
        "imgDesc35": "Diese Person ist auf LinkedIn.",
        "imgDesc37": "Diese Person ist auf LinkedIn.",
        "imgDesc39": "Diese Person ist auf LinkedIn.",
        "imgDesc41": "Diese Person ist auf LinkedIn.",
        "imgDesc43": "Diese Person ist auf LinkedIn.",
        "imgDesc45": "Diese Person ist auf LinkedIn.",
        "imgDesc47": "Diese Person ist auf LinkedIn.",
        "imgDesc49": "Diese Person ist auf LinkedIn.",
        "professionalOrCriminal": "Profi oder Verbrecher?",
        "youDecide": "Du entscheidest!",
        "aDeductionGame": "Ein Deduktionsspiel",
        "version": "Version 1.0",
        "disclaimer": "Haftungsausschluss: Diese Website ist ein satirisches und lehrreiches Ratespiel.",
        "allRightsReserved": "Alle Rechte vorbehalten.",
        "metaDescription": "Ein lustiges Spiel, bei dem du erraten musst, ob eine Person ein LinkedIn-Profi oder ein Interpol-Verbrecher ist.",
        "ogTitle": "LinkedIn oder Interpol",
        "ogDescription": "Ein lustiges Spiel, bei dem du erraten musst, ob eine Person ein LinkedIn-Profi oder ein Interpol-Verbrecher ist.",
        "aboutTitle": "Über - LinkedIn oder Interpol",
        "aboutHeader": "Über das Spiel",
        "aboutText": "Dieses Spiel wurde zu Unterhaltungs- und Bildungszwecken erstellt, um die Ähnlichkeiten und Unterschiede in Berufs- und Kriminellenprofilen aufzuzeigen. Alle Bilder werden zu satirischen Zwecken verwendet.",
        "disclaimerTitle": "Haftungsausschluss - LinkedIn oder Interpol",
        "disclaimerHeader": "Haftungsausschluss",
        "disclaimerText": "Diese Website ist ein satirisches und lehrreiches Ratespiel. Sie ist nicht mit LinkedIn oder Interpol verbunden. Alle Inhalte dienen nur zu Unterhaltungszwecken.",
        "backButton": "Zurück zum Spiel",
        "aboutButton": "Über",
        "disclaimerButton": "Haftungsausschluss",
        "metaKeywords": "linkedin, interpol, spiel, profi, verbrecher, raten"
    },
    "pt": {
        "title": "LinkedIn ou Interpol",
        "subtitle": "Profissional ou Criminoso? Você decide!",
        "score": "Pontuação",
        "total": "Total",
        "autoAdvance": "Avanço Automático",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Próxima Imagem",
        "footerTitle": "LinkedIn ou Interpol - Um Jogo de Dedução - Versão 1.0",
        "footerDisclaimer": "Aviso: Este site é um jogo de adivinhação satírico e educacional.",
        "privacyPolicy": "Política de Privacidade",
        "termsOfService": "Termos de Serviço",
        "copyright": "© 2025 Jan Queralt. Todos os direitos reservados.",
        "correct": "Correto!",
        "wrong": "Errado!",
        "policeRecord": "Ficha Criminal",
        "imgDesc1": "Esta pessoa está no LinkedIn.",
        "imgDesc2": "Iraniano indiciado por hacking pelo FBI.",
        "imgDesc3": "Esta pessoa está no LinkedIn.",
        "imgDesc4": "Caso de tráfico e distribuição de drogas pelo FBI.",
        "imgDesc5": "Esta pessoa está no LinkedIn.",
        "imgDesc6": "Acusações de conspiração e agente estrangeiro.",
        "imgDesc7": "Esta pessoa está no LinkedIn.",
        "imgDesc8": "Kulkov indiciado por cibercrime.",
        "imgDesc9": "Esta pessoa está no LinkedIn.",
        "imgDesc10": "Radovanovic acusado de conspiração de swatting.",
        "imgDesc11": "Esta pessoa está no LinkedIn.",
        "imgDesc12": "Sokolov indiciado por fraude de cartão de crédito.",
        "imgDesc13": "Esta pessoa está no LinkedIn.",
        "imgDesc14": "Conspiração de tráfico de fentanil e armas.",
        "imgDesc15": "Esta pessoa está no LinkedIn.",
        "imgDesc16": "Acusações de conspiração para distribuição de drogas.",
        "imgDesc17": "Esta pessoa está no LinkedIn.",
        "imgDesc18": "faz parte da organização criminosa PSOE",
        "imgDesc19": "Esta pessoa está no LinkedIn.",
        "imgDesc20": "Rapto de criança por Smrekar.",
        "imgDesc21": "Esta pessoa está no LinkedIn.",
        "imgDesc22": "Mandados de prisão internacionais emitidos por conspiração para assassinato.",
        "imgDesc23": "Esta pessoa está no LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO procurado por roubo de cocaína.",
        "imgDesc25": "Esta pessoa está no LinkedIn.",
        "imgDesc26": "procurado por corrupção em Taiwan.",
        "imgDesc27": "Esta pessoa está no LinkedIn.",
        "imgDesc28": "Acusações de terrorismo e cibercrime.",
        "imgDesc29": "Esta pessoa está no LinkedIn.",
        "imgDesc30": "procurado por homicídio e tentativa de homicídio.",
        "imgDesc31": "Esta pessoa está no LinkedIn.",
        "imgDesc32": "Lester Eubanks procurado por homicídio e fuga.",
        "imgDesc33": "Esta pessoa está no LinkedIn.",
        "imgDesc35": "Esta pessoa está no LinkedIn.",
        "imgDesc37": "Esta pessoa está no LinkedIn.",
        "imgDesc39": "Esta pessoa está no LinkedIn.",
        "imgDesc41": "Esta pessoa está no LinkedIn.",
        "imgDesc43": "Esta pessoa está no LinkedIn.",
        "imgDesc45": "Esta pessoa está no LinkedIn.",
        "imgDesc47": "Esta pessoa está no LinkedIn.",
        "imgDesc49": "Esta pessoa está no LinkedIn.",
        "professionalOrCriminal": "Profissional ou Criminoso?",
        "youDecide": "Você decide!",
        "aDeductionGame": "Um Jogo de Dedução",
        "version": "Versão 1.0",
        "disclaimer": "Aviso: Este site é um jogo de adivinhação satírico e educacional.",
        "allRightsReserved": "Todos os direitos reservados.",
        "metaDescription": "Um jogo divertido onde você tem que adivinhar se uma pessoa é um profissional do LinkedIn ou um criminoso da Interpol.",
        "ogTitle": "LinkedIn ou Interpol",
        "ogDescription": "Um jogo divertido onde você tem que adivinhar se uma pessoa é um profissional do LinkedIn ou um criminoso da Interpol.",
        "aboutTitle": "Sobre - LinkedIn ou Interpol",
        "aboutHeader": "Sobre o Jogo",
        "aboutText": "Este jogo foi criado para fins de entretenimento e educacionais para destacar as semelhanças e diferenças nos perfis profissionais e criminosos. Todas as imagens são usadas para fins satíricos.",
        "disclaimerTitle": "Aviso Legal - LinkedIn ou Interpol",
        "disclaimerHeader": "Aviso Legal",
        "disclaimerText": "Este site é um jogo de adivinhação satírico e educacional. Não é afiliado ao LinkedIn ou à Interpol. Todo o conteúdo é apenas para fins de entretenimento.",
        "backButton": "Voltar ao jogo",
        "aboutButton": "Sobre",
        "disclaimerButton": "Aviso Legal",
        "metaKeywords": "linkedin, interpol, jogo, profissional, criminoso, adivinhar"
    },
    "it": {
        "title": "LinkedIn o Interpol",
        "subtitle": "Professionista o Criminale? Tu decidi!",
        "score": "Punteggio",
        "total": "Totale",
        "autoAdvance": "Avanzamento Automatico",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Immagine Successiva",
        "footerTitle": "LinkedIn o Interpol - Un Gioco di Deduzione - Versione 1.0",
        "footerDisclaimer": "Disclaimer: Questo sito web è un gioco di indovinelli satirico ed educativo.",
        "privacyPolicy": "Informativa sulla Privacy",
        "termsOfService": "Termini di Servizio",
        "copyright": "© 2025 Jan Queralt. Tutti i diritti riservati.",
        "correct": "Corretto!",
        "wrong": "Sbagliato!",
        "policeRecord": "Precedenti Penali",
        "imgDesc1": "Questa persona è su LinkedIn.",
        "imgDesc2": "Iraniano incriminato per hacking dall'FBI.",
        "imgDesc3": "Questa persona è su LinkedIn.",
        "imgDesc4": "Caso di traffico e distribuzione di droga dall'FBI.",
        "imgDesc5": "Questa persona è su LinkedIn.",
        "imgDesc6": "Accuse di cospirazione e agente straniero.",
        "imgDesc7": "Questa persona è su LinkedIn.",
        "imgDesc8": "Kulkov incriminato per cybercrime.",
        "imgDesc9": "Questa persona è su LinkedIn.",
        "imgDesc10": "Radovanovic accusato di cospirazione per swatting.",
        "imgDesc11": "Questa persona è su LinkedIn.",
        "imgDesc12": "Sokolov incriminato per frode con carta di credito.",
        "imgDesc13": "Questa persona è su LinkedIn.",
        "imgDesc14": "Cospirazione per il traffico di fentanil e armi.",
        "imgDesc15": "Questa persona è su LinkedIn.",
        "imgDesc16": "Accuse di cospirazione per la distribuzione di droga.",
        "imgDesc17": "Questa persona è su LinkedIn.",
        "imgDesc18": "fa parte dell'organizzazione criminale PSOE",
        "imgDesc19": "Questa persona è su LinkedIn.",
        "imgDesc20": "Rapimento di minore da parte di Smrekar.",
        "imgDesc21": "Questa persona è su LinkedIn.",
        "imgDesc22": "Mandati di arresto internazionali emessi per complotto di omicidio.",
        "imgDesc23": "Questa persona è su LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO ricercato per rapina di cocaina.",
        "imgDesc25": "Questa persona è su LinkedIn.",
        "imgDesc26": "ricercato per corruzione a Taiwan.",
        "imgDesc27": "Questa persona è su LinkedIn.",
        "imgDesc28": "Accuse di terrorismo e cybercrime.",
        "imgDesc29": "Questa persona è su LinkedIn.",
        "imgDesc30": "ricercato per omicidio e tentato omicidio.",
        "imgDesc31": "Questa persona è su LinkedIn.",
        "imgDesc32": "Lester Eubanks ricercato per omicidio ed evasione.",
        "imgDesc33": "Questa persona è su LinkedIn.",
        "imgDesc35": "Questa persona è su LinkedIn.",
        "imgDesc37": "Questa persona è su LinkedIn.",
        "imgDesc39": "Questa persona è su LinkedIn.",
        "imgDesc41": "Questa persona è su LinkedIn.",
        "imgDesc43": "Questa persona è su LinkedIn.",
        "imgDesc45": "Questa persona è su LinkedIn.",
        "imgDesc47": "Questa persona è su LinkedIn.",
        "imgDesc49": "Questa persona è su LinkedIn.",
        "professionalOrCriminal": "Professionista o Criminale?",
        "youDecide": "Tu decidi!",
        "aDeductionGame": "Un Gioco di Deduzione",
        "version": "Versione 1.0",
        "disclaimer": "Disclaimer: Questo sito web è un gioco di indovinelli satirico ed educativo.",
        "allRightsReserved": "Tutti i diritti riservati.",
        "metaDescription": "Un gioco divertente in cui devi indovinare se una persona è un professionista di LinkedIn o un criminale dell'Interpol.",
        "ogTitle": "LinkedIn o Interpol",
        "ogDescription": "Un gioco divertente in cui devi indovinare se una persona è un professionista di LinkedIn o un criminale dell'Interpol.",
        "aboutTitle": "Informazioni - LinkedIn o Interpol",
        "aboutHeader": "Informazioni sul Gioco",
        "aboutText": "Questo gioco è stato creato per scopi di intrattenimento ed educativi per evidenziare le somiglianze e le differenze nei profili professionali e criminali. Tutte le immagini sono utilizzate a scopo satirico.",
        "disclaimerTitle": "Disclaimer - LinkedIn o Interpol",
        "disclaimerHeader": "Disclaimer",
        "disclaimerText": "Questo sito web è un gioco di indovinelli satirico ed educativo. Non è affiliato a LinkedIn o Interpol. Tutti i contenuti sono solo a scopo di intrattenimento.",
        "backButton": "Torna al gioco",
        "aboutButton": "Informazioni",
        "disclaimerButton": "Disclaimer",
        "metaKeywords": "linkedin, interpol, gioco, professionista, criminale, indovinare"
    },
    "nl": {
        "title": "LinkedIn of Interpol",
        "subtitle": "Professional of Crimineel? Jij beslist!",
        "score": "Score",
        "total": "Totaal",
        "autoAdvance": "Automatisch Doorgaan",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Interpol",
        "nextButton": "Volgende Afbeelding",
        "footerTitle": "LinkedIn of Interpol - Een Deductiespel - Versie 1.0",
        "footerDisclaimer": "Disclaimer: Deze website is een satirisch en educatief raadspel.",
        "privacyPolicy": "Privacybeleid",
        "termsOfService": "Servicevoorwaarden",
        "copyright": "© 2025 Jan Queralt. Alle rechten voorbehouden.",
        "correct": "Correct!",
        "wrong": "Fout!",
        "policeRecord": "Politierapport",
        "imgDesc1": "Deze persoon staat op LinkedIn.",
        "imgDesc2": "Iraniër aangeklaagd voor hacken door de FBI.",
        "imgDesc3": "Deze persoon staat op LinkedIn.",
        "imgDesc4": "Zaak van drugshandel en -distributie door de FBI.",
        "imgDesc5": "Deze persoon staat op LinkedIn.",
        "imgDesc6": "Aanklacht wegens samenzwering en buitenlandse agent.",
        "imgDesc7": "Deze persoon staat op LinkedIn.",
        "imgDesc8": "Kulkov aangeklaagd voor cybercriminaliteit.",
        "imgDesc9": "Deze persoon staat op LinkedIn.",
        "imgDesc10": "Radovanovic beschuldigd van swatting-samenzwering.",
        "imgDesc11": "Deze persoon staat op LinkedIn.",
        "imgDesc12": "Sokolov aangeklaagd voor creditcardfraude.",
        "imgDesc13": "Deze persoon staat op LinkedIn.",
        "imgDesc14": "Samenzwering voor de handel in fentanyl en wapens.",
        "imgDesc15": "Deze persoon staat op LinkedIn.",
        "imgDesc16": "Aanklacht wegens samenzwering voor drugshandel.",
        "imgDesc17": "Deze persoon staat op LinkedIn.",
        "imgDesc18": "maakt deel uit van de criminele organisatie PSOE",
        "imgDesc19": "Deze persoon staat op LinkedIn.",
        "imgDesc20": "Kinderontvoering door Smrekar.",
        "imgDesc21": "Deze persoon staat op LinkedIn.",
        "imgDesc22": "Internationale arrestatiebevelen uitgevaardigd voor moordcomplot.",
        "imgDesc23": "Deze persoon staat op LinkedIn.",
        "imgDesc24": "Steffen van Khoa DO gezocht voor cocaïneroof.",
        "imgDesc25": "Deze persoon staat op LinkedIn.",
        "imgDesc26": "gezocht voor corruptie in Taiwan.",
        "imgDesc27": "Deze persoon staat op LinkedIn.",
        "imgDesc28": "Aanklacht wegens terrorisme en cybercriminaliteit.",
        "imgDesc29": "Deze persoon staat op LinkedIn.",
        "imgDesc30": "gezocht voor moord en poging tot moord.",
        "imgDesc31": "Deze persoon staat op LinkedIn.",
        "imgDesc32": "Lester Eubanks gezocht voor moord en ontsnapping.",
        "imgDesc33": "Deze persoon staat op LinkedIn.",
        "imgDesc35": "Deze persoon staat op LinkedIn.",
        "imgDesc37": "Deze persoon staat op LinkedIn.",
        "imgDesc39": "Deze persoon staat op LinkedIn.",
        "imgDesc41": "Deze persoon staat op LinkedIn.",
        "imgDesc43": "Deze persoon staat op LinkedIn.",
        "imgDesc45": "Deze persoon staat op LinkedIn.",
        "imgDesc47": "Deze persoon staat op LinkedIn.",
        "imgDesc49": "Deze persoon staat op LinkedIn.",
        "professionalOrCriminal": "Professional of Crimineel?",
        "youDecide": "Jij beslist!",
        "aDeductionGame": "Een Deductiespel",
        "version": "Versie 1.0",
        "disclaimer": "Disclaimer: Deze website is een satirisch en educatief raadspel.",
        "allRightsReserved": "Alle rechten voorbehouden.",
        "metaDescription": "Een leuk spel waarbij je moet raden of een persoon een LinkedIn-professional of een Interpol-crimineel is.",
        "ogTitle": "LinkedIn of Interpol",
        "ogDescription": "Een leuk spel waarbij je moet raden of een persoon een LinkedIn-professional of een Interpol-crimineel is.",
        "aboutTitle": "Over - LinkedIn of Interpol",
        "aboutHeader": "Over het Spel",
        "aboutText": "Dit spel is gemaakt voor amusements- en educatieve doeleinden om de overeenkomsten en verschillen in professionele en criminele profielen te benadrukken. Alle afbeeldingen worden gebruikt voor satirische doeleinden.",
        "disclaimerTitle": "Disclaimer - LinkedIn of Interpol",
        "disclaimerHeader": "Disclaimer",
        "disclaimerText": "Deze website is een satirisch en educatief raadspel. Het is niet gelieerd aan LinkedIn of Interpol. Alle inhoud is uitsluitend voor amusementsdoeleinden.",
        "backButton": "Terug naar het spel",
        "aboutButton": "Over",
        "disclaimerButton": "Disclaimer",
        "metaKeywords": "linkedin, interpol, spel, professional, crimineel, raden"
    },
    "ru": {
        "title": "LinkedIn или Интерпол",
        "subtitle": "Профессионал или преступник? Решайте!",
        "score": "Счет",
        "total": "Всего",
        "autoAdvance": "Автоматический переход",
        "linkedinButton": "LinkedIn",
        "interpolButton": "Интерпол",
        "nextButton": "Следующее изображение",
        "footerTitle": "LinkedIn или Интерпол - Детективная игра - Версия 1.0",
        "footerDisclaimer": "Отказ от ответственности: Этот сайт является сатирической и образовательной игрой-угадайкой.",
        "privacyPolicy": "Политика конфиденциальности",
        "termsOfService": "Условия использования",
        "copyright": "© 2025 Jan Queralt. Все права защищены.",
        "correct": "Правильно!",
        "wrong": "Неправильно!",
        "policeRecord": "Полицейское досье",
        "imgDesc1": "Этот человек на LinkedIn.",
        "imgDesc2": "Иранец, обвиненный ФБР во взломе.",
        "imgDesc3": "Этот человек на LinkedIn.",
        "imgDesc4": "Дело о незаконном обороте и распространении наркотиков ФБР.",
        "imgDesc5": "Этот человек на LinkedIn.",
        "imgDesc6": "Обвинения в заговоре и деятельности в качестве иностранного агента.",
        "imgDesc7": "Этот человек на LinkedIn.",
        "imgDesc8": "Кульков обвинен в киберпреступности.",
        "imgDesc9": "Этот человек на LinkedIn.",
        "imgDesc10": "Радованович обвинен в сговоре с целью своттинга.",
        "imgDesc11": "Этот человек на LinkedIn.",
        "imgDesc12": "Соколов обвинен в мошенничестве с кредитными картами.",
        "imgDesc13": "Этот человек на LinkedIn.",
        "imgDesc14": "Заговор с целью незаконного оборота фентанила и оружия.",
        "imgDesc15": "Этот человек на LinkedIn.",
        "imgDesc16": "Обвинения в сговоре с целью распространения наркотиков.",
        "imgDesc17": "Этот человек на LinkedIn.",
        "imgDesc18": "является частью преступной организации PSOE",
        "imgDesc19": "Этот человек на LinkedIn.",
        "imgDesc20": "Похищение ребенка Смрекаром.",
        "imgDesc21": "Этот человек на LinkedIn.",
        "imgDesc22": "Выданы международные ордера на арест за сговор с целью убийства.",
        "imgDesc23": "Этот человек на LinkedIn.",
        "imgDesc24": "Стеффен ван Хоа ДО разыскивается за ограбление с кокаином.",
        "imgDesc25": "Этот человек на LinkedIn.",
        "imgDesc26": "разыскивается за коррупцию на Тайване.",
        "imgDesc27": "Этот человек на LinkedIn.",
        "imgDesc28": "Обвинения в терроризме и киберпреступности.",
        "imgDesc29": "Этот человек на LinkedIn.",
        "imgDesc30": "разыскивается за убийство и покушение на убийство.",
        "imgDesc31": "Этот человек на LinkedIn.",
        "imgDesc32": "Лестер Юбэнкс разыскивается за убийство и побег.",
        "imgDesc33": "Этот человек на LinkedIn.",
        "imgDesc35": "Этот человек на LinkedIn.",
        "imgDesc37": "Этот человек на LinkedIn.",
        "imgDesc39": "Этот человек на LinkedIn.",
        "imgDesc41": "Этот человек на LinkedIn.",
        "imgDesc43": "Этот человек на LinkedIn.",
        "imgDesc45": "Этот человек на LinkedIn.",
        "imgDesc47": "Этот человек на LinkedIn.",
        "imgDesc49": "Этот человек на LinkedIn.",
        "professionalOrCriminal": "Профессионал или преступник?",
        "youDecide": "Решайте!",
        "aDeductionGame": "Детективная игра",
        "version": "Версия 1.0",
        "disclaimer": "Отказ от ответственности: Этот сайт является сатирической и образовательной игрой-угадайкой.",
        "allRightsReserved": "Все права защищены.",
        "metaDescription": "Забавная игра, в которой вам предстоит угадать, является ли человек профессионалом из LinkedIn или преступником из Интерпола.",
        "ogTitle": "LinkedIn или Интерпол",
        "ogDescription": "Забавная игра, в которой вам предстоит угадать, является ли человек профессионалом из LinkedIn или преступником из Интерпола.",
        "aboutTitle": "О - LinkedIn или Интерпол",
        "aboutHeader": "Об игре",
        "aboutText": "Эта игра была создана в развлекательных и образовательных целях, чтобы подчеркнуть сходства и различия в профессиональных и криминальных профилях. Все изображения используются в сатирических целях.",
        "disclaimerTitle": "Отказ от ответственности - LinkedIn или Интерпол",
        "disclaimerHeader": "Отказ от ответственности",
        "disclaimerText": "Этот сайт является сатирической и образовательной игрой-угадайкой. Он не связан с LinkedIn или Интерполом. Весь контент предназначен исключительно для развлекательных целей.",
        "backButton": "Назад к игре",
        "aboutButton": "О",
        "disclaimerButton": "Отказ от ответственности",
        "metaKeywords": "linkedin, интерпол, игра, профессионал, преступник, угадать"
    }
};

const images = [
    // 50 imágenes reales con URLs corregidas
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc1' },
    { src: 'https://www.fbi.gov/wanted/cyber/mohammed-reza-sabahi/@@images/image/preview', type: 'interpol', name: 'Mohammed Reza Sabahi', recordUrl: 'https://www.fbi.gov/wanted/cyber/mohammed-reza-sabahi', descriptionKey: 'imgDesc2' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc3' },
    { src: 'https://www.fbi.gov/wanted/cei/john-joe-soto/@@images/image/preview', type: 'interpol', name: 'John Joe Soto', recordUrl: 'https://www.fbi.gov/wanted/cei/john-joe-soto', descriptionKey: 'imgDesc4' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc5' },
    { src: 'https://www.fbi.gov/wanted/counterintelligence/natalia-burlinova/@@images/image/preview', type: 'interpol', name: 'Natalia Burlinova', recordUrl: 'https://www.fbi.gov/wanted/counterintelligence/natalia-burlinova', descriptionKey: 'imgDesc6' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc7' },
    { src: 'https://www.secretservice.gov/sites/default/files/styles/500px_width/public/2023-05/kulkov_200x.png.webp?itok=QEpJMkNO', type: 'interpol', name: 'Kulkov', recordUrl: 'https://www.secretservice.gov/investigations/mostwanted/kulkov', descriptionKey: 'imgDesc8' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc9' },
    { src: 'https://www.secretservice.gov/sites/default/files/styles/webp_original_size/public/2024-08/RADOVANOVIC-Nemanja-Photo1.jpg.webp?itok=0C6RbHlg', type: 'interpol', name: 'Nemanja Radovanovic', recordUrl: 'https://www.secretservice.gov/investigations/mostwanted/radovanovic', descriptionKey: 'imgDesc10' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc11' },
    { src: 'https://www.secretservice.gov/sites/default/files/styles/webp_original_size/public/inline-images/sokolov-5.png.webp?itok=amNSVvhX', type: 'interpol', name: 'Sokolov', recordUrl: 'https://www.secretservice.gov/investigations/mostwanted/sokolov', descriptionKey: 'imgDesc12' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc13' },
    { src: 'https://www.dea.gov/sites/default/files/2023-04/Nunez-Herrera%2C%20Alan%20Gabriel.jpg', type: 'interpol', name: 'Alan Gabriel Nunez-Herrera', recordUrl: 'https://www.dea.gov/fugitives/alan-gabriel-nunez-herrera', descriptionKey: 'imgDesc14' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc15' },
    { src: 'https://www.dea.gov/sites/default/files/fugitives/fugitives/elp/hernandez-de-la-cruz.jpg', type: 'interpol', name: 'Hernandez De La Cruz', recordUrl: 'https://www.dea.gov/fugitives/benjamin-hernandez-de-la-cruz', descriptionKey: 'imgDesc16' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc17' },
    { src: 'https://www.lamoncloa.gob.es/presidente/PublishingImages/SANCHEZ-BIOGRAFIA/080323-sanchez-biografia2.jpg', type: 'interpol', name: 'Pedro Sanchez', recordUrl: 'https://es.wikipedia.org/wiki/Pedro_Sánchez', descriptionKey: 'imgDesc18' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc19' },
    { src: 'https://eumostwanted.eu/sites/default/files/styles/wanted_medium/public/wanted_pictures/Smrekar%20Melisa%203.jpg?itok=vDOAEXxQ', type: 'interpol', name: 'Melisa Smrekar', recordUrl: 'https://eumostwanted.eu/#/index.php/smrekar-melisa', descriptionKey: 'imgDesc20' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc21' },
    { src: 'https://eumostwanted.eu/sites/default/files/styles/wanted_medium/public/wanted_pictures/eva.png?itok=5JJlDQPH', type: 'interpol', name: 'Eva', recordUrl: 'https://eumostwanted.eu/#/zamecnikova-eva', descriptionKey: 'imgDesc22' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc23' },
    { src: 'https://eumostwanted.eu/sites/default/files/styles/wanted_medium/public/wanted_pictures/4_dk_-_steffen-van-khoa-do.jpg?itok=yH_UD9cK', type: 'interpol', name: 'Steffen van Khoa DO', recordUrl: 'https://eumostwanted.eu/#/do-steffen-van-khoa', descriptionKey: 'imgDesc24' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc25' },
    { src: 'https://www.cib.npa.gov.tw/en/app/globalcase/image?module=globalcase&detailNo=782819431024717824&init=Y', type: 'interpol', name: 'Unknown', recordUrl: 'https://www.cib.npa.gov.tw/en/', descriptionKey: 'imgDesc26' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc27' },
    { src: 'https://eumostwanted.eu/sites/default/files/styles/wanted_medium/public/wanted_pictures/Imagen%202.png?itok=aEniB5aK', type: 'interpol', name: 'Unknown', recordUrl: 'https://eumostwanted.eu/', descriptionKey: 'imgDesc28' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc29' },
    { src: 'https://www.usmarshals.gov/sites/default/files/acquiadam/most-wanted-king-robert-lee-300-350.jpg', type: 'interpol', name: 'Robert Lee King', recordUrl: 'https://www.usmarshals.gov/what-we-do/fugitive-apprehension/15-most-wanted-fugitive/robert-lee-king', descriptionKey: 'imgDesc30' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc31' },
    { src: 'https://www.usmarshals.gov/sites/default/files/acquiadam/most-wanted-eubanks-lester-edward-300-350.jpg', type: 'interpol', name: 'Lester Edward Eubanks', recordUrl: 'https://www.usmarshals.gov/what-we-do/fugitive-apprehension/15-most-wanted-fugitive/lester-eubanks', descriptionKey: 'imgDesc32' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc33' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc35' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc37' },
    { src: 'https://thispersondoesnotexist.com/', type: "linkedin", descriptionKey: 'imgDesc39' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc41' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc43' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc45' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc47' },
    { src: 'https://thispersondoesnotexist.com/', type: 'linkedin', descriptionKey: 'imgDesc49' },
];

let score = 0;
let total = 0;
let currentImage;
let remainingImages = [...images];
let autoAdvance = true;
let currentTranslations = {};

const profilePicture = document.getElementById('profile-picture');
const scoreSpan = document.getElementById('score');
const totalSpan = document.getElementById('total');
const linkedinButton = document.getElementById('linkedin-button');
const interpolButton = document.getElementById('interpol-button');
const feedbackEl = document.getElementById('feedback');
const descriptionEl = document.getElementById('description');
const nextButton = document.getElementById('next-button');
const autoAdvanceSwitch = document.getElementById('auto-advance-switch');
const languageSelector = document.getElementById('language-selector');

function loadLanguage(lang) {
    currentTranslations = translations[lang];
    translatePage();
    updateMetaTags();
}

function translatePage() {
    document.querySelectorAll('[data-i18n-key]').forEach(el => {
        const key = el.getAttribute('data-i18n-key');
        if (currentTranslations[key]) {
            el.textContent = currentTranslations[key];
        }
    });
}

function updateMetaTags() {
    document.querySelector('meta[name="description"]').setAttribute('content', currentTranslations.metaDescription);
    document.querySelector('meta[property="og:title"]').setAttribute('content', currentTranslations.ogTitle);
    document.querySelector('meta[property="og:description"]').setAttribute('content', currentTranslations.ogDescription);
    document.querySelector('meta[name="keywords"]').setAttribute('content', currentTranslations.metaKeywords);
}

function nextImage() {
    feedbackEl.textContent = '';
    feedbackEl.className = '';
    descriptionEl.textContent = '';
    nextButton.classList.add('hidden');
    linkedinButton.disabled = false;
    interpolButton.disabled = false;

    if (remainingImages.length === 0) {
        // Reshuffle the images to play again
        remainingImages = [...images];
    }

    const randomIndex = Math.floor(Math.random() * remainingImages.length);
    currentImage = remainingImages.splice(randomIndex, 1)[0];
    profilePicture.src = currentImage.src;
    total++;
    totalSpan.textContent = total;
}

function checkAnswer(guess) {
    if (guess === currentImage.type) {
        score++;
        scoreSpan.textContent = score;
        feedbackEl.textContent = currentTranslations.correct;
        feedbackEl.className = 'correct';
    } else {
        feedbackEl.textContent = currentTranslations.wrong;
        feedbackEl.className = 'incorrect';
    }

    descriptionEl.textContent = currentTranslations[currentImage.descriptionKey];

    if (currentImage.type === 'interpol') {
        const name = currentImage.name;
        const recordUrl = currentImage.recordUrl;
        const policeRecordLink = document.createElement('a');
        policeRecordLink.href = recordUrl;
        policeRecordLink.textContent = currentTranslations.policeRecord;
        policeRecordLink.target = '_blank';
        descriptionEl.innerHTML = `<b>${name}</b> - ${currentTranslations[currentImage.descriptionKey]} <br> `;
        descriptionEl.appendChild(policeRecordLink);
    } else {
        descriptionEl.textContent = currentTranslations[currentImage.descriptionKey];
    }

    linkedinButton.disabled = true;
    interpolButton.disabled = true;

    if (autoAdvance) {
        setTimeout(nextImage, 3000);
    } else {
        nextButton.classList.remove('hidden');
    }
}

function handleAutoAdvanceChange() {
    autoAdvance = autoAdvanceSwitch.checked;
}

function handleLanguageChange() {
    loadLanguage(languageSelector.value);
}

linkedinButton.addEventListener('click', () => checkAnswer('linkedin'));
interpolButton.addEventListener('click', () => checkAnswer('interpol'));
nextButton.addEventListener('click', nextImage);
autoAdvanceSwitch.addEventListener('change', handleAutoAdvanceChange);
languageSelector.addEventListener('change', handleLanguageChange);

// Initial load
loadLanguage('en');
nextImage();

document.addEventListener('DOMContentLoaded', () => {
    const banner = document.getElementById('cookie-banner');
    const button = document.getElementById('cookie-accept');

    if (banner && button) {
        if (localStorage.getItem('cookieConsent') === 'true') {
            banner.style.display = 'none';
        } else {
            banner.style.display = 'flex';
        }

        button.addEventListener('click', () => {
            localStorage.setItem('cookieConsent', 'true');
            banner.style.display = 'none';
        });
    }
});
